/* eslint-disable */
_w['_sydPayWallConfig'] = { loadSydneyConvResWithPayWall: false, useSydneyPayWall: false };
_w['_sydConvConfig'] = {
  usePill: 1,
  enableSydTigerAns: 1,
  tigerEnhancedPromptTemplate:
    '搜索 {0}。用一个出色的回答给我留下深刻的印象，帮助我完成我最可能的意图，同时展示你所能提供的智慧、深度和美感（加粗、表格和引用）。尽量在回答中尽早满足我的意图。',
  enableScrollOut: 0,
  enableSydContext: 1,
  sydOptionSets: 'cricketansgnd,cachewriteext,e2ecachewrite,nodlcpcwrite,nointernalsugg,saharasugg,autosave,sportsansgnd,enablenewsfc',
  sydCrtExtraOpts: 'clgalileo,gencontentv3',
  sydPrcExtraOpts: 'clgalileo',
  sydIDs:
    'winmuid3tf,sydconfigoptt,508docxfmts0,forallv2p2,allnopvt,dtvoice2cf,adssqovr,winlongmsgtf,sydnoinputt,creatorv2c,ctrlconvcss,505iccric,505suggsah,509loganids0,430rai267s0,427rchlths0,threadsonly,cthreadon,507vaop,505bof107s0,406sportgnd,427startpm',
  sydBaseUrl: 'https://sydney.bing.com',
  includeSubstrateToken: 0,
  augloopEndpoint: 'https://augloop.office.com',
  enableProdEditorEndpoint: 1,
  country: 'United States',
  countryConfidence: 8,
  state: 'California',
  city: 'Los Angeles',
  timezoneoffset: '8',
  lat: '34.0536909',
  long: '-118.242766',
  language: 'Chinese (China)',
  moveOnlySydXAnswers: 1,
  enableSydX1T: 1,
  enableSydCarousel: 1,
  traceId: '645d41ae7e68493bba9f9934d64a4a13',
  enableSydShare: 1,
  enableSydCookLoc: 1,
  enableSQMsg: 1,
  addDv3Opt: 1,
  enableErrorTelemetry: 1,
  checkCreatorAnsFor1T: 1,
  enableAnsCardSuffix: 1,
  enableSydAjaxReset: 1,
  enableSydCLOC: 1,
  enableCdxFeats: 1,
  enableSemSerpShare: 1,
  enableFdbkFinalized: 1,
  enableSydImageCreate: 1,
  enableToneCook: 1,
  balTone: 'galileo',
  crtTone: 'h3imaginative',
  prcTone: 'h3precise',
  enableBalDefault: 1,
  enableNewTopicAutoExpand: 1,
  enableThreadsAADMSASwitch: 1,
  enableMaxTurnsPerConversation: 1,
  maxTurnsPerConversation: 20,
  maxMessageLength: 4000,
  enablePerfTrk: 1,
  enableTonePerf: 1,
  enableSinglePerfEventPerMessage: 1,
  enableAdSlugsMobile: 1,
  enableCreatorShare: 1,
  enableUnauthRedir: 1,
  enableAddMobileTagToCibOnShowConv: 1,
  enableMMAnsType: 1,
  enableStreamSyntheticTextResponses: 1,
  syntheticStreamSpeed: 55,
  enableServerLogMerging: 1,
  enableAutoRecoverFromInvalidSession: 1,
  enableAutoRecoverFromInvalidSessionForFirstTurn: 1,
  enableCodeCopy: 1,
  enableRichTextPaste: 1,
  enableActionBarIMEFix: 1,
  enableFeedbackInstrumentation: 1,
  sydneySapphireUpsellTreatment: 4,
  enableSearchQueryForInlineAds: 1,
  enableFixCodeXAsBug: 1,
  enableThreads: 1,
  enablePreserveTextFormat: 1,
  disable2TSearchHistory: 1,
  enableSydBeacon: 1,
  suppressPoleRSWhenEnableSydCarousel: 1,
  disablePassBotGreetingInContext: 1,
  enableCloudflareCaptcha: 1,
  enableResizeObserverWithAnimationFrame: 1,
  enableStartPromotion: 1,
  enableCopyButtonInstrumented: 1,
  enableGetChats: 1,
  enableThreadSync: 1,
  enableBICHistory: 1,
};
_w['_sydThreads'] = { threads: [] };
_w['_sydConvTranslation'] = {
  actionBarPlaceholder: '有问题尽管问我...（Shift + Enter = 换行，"/" 触发提示词）',
  actionBarAriaLabel: '询问必应',
  actionBarComposeButton: '新主题',
  actionBarNewChatButtonDesktop: '开始新聊天',
  actionBarNewChatButtonMobile: '新建聊天',
  actionBarOngoingConvPlaceholder: '键入消息',
  captchaTitle: '验证身份',
  captchaDescription: '若要继续，请在下图中输入字符。',
  captchaPlaceholder: '输入字符...',
  captchaPlaceholderError: '抱歉，请重试。',
  next: '下一步',
  cancel: '取消',
  feedbackAccessed: '访问时间',
  feedbackSource: '源: 与必应的对话，',
  feedbackShareConversationQuery: '什么是新版必应?',
  messageLearnMore: '了解详细信息:',
  letsChat: '我们聊天吧',
  pause: '暂停',
  play: '开始游戏',
  speechFailedRecognitionError: '抱歉，我无法收听你的声音，因为语音服务器已关闭，请稍后再试。',
  speechListening: '我听着呢...',
  speechLoading: '正在等待音频...',
  speechMediaNotReachableError: '很抱歉，我无法收听你的声音，因为你没有可用的麦克风。',
  speechNoPermissionError: '你需要启用麦克风，我才能听到你的声音。',
  speechAudioPlaybackError: '出错了。',
  stop: '停止',
  welcomeContainerPrivacyStatement: '隐私声明',
  welcomeContainerUseTerms: '使用条款',
  welcomeMessageItemContent1: '我可以为我挑剔的只吃橙色食物的孩子做什么饭?',
  welcomeMessageItemContent2: '销量最高的 3 种宠物吸尘器有哪些优点和缺点?',
  welcomeMessageItemContent3: '以海盗的口吻写一首关于外太空鳄鱼的俳句',
  welcomeMessageItemTitle1: '🧐 提出复杂问题',
  welcomeMessageItemTitle2: '🙌获取更好的答案',
  welcomeMessageItemTitle3: '🎨 获得创意灵感',
  welcomeMessageItemLabel4: '更多创意中的新增功能：',
  warmWelcomeTitle: '欢迎使用新必应',
  welcomeSubtitleText: '由 AI 支持的网页版 Copilot',
  workToggleDescription: '以及你的结果包括哪些内容',
  feedbackFirstMessage: '非常抱歉没有帮助到你。是否可以详细说明你不喜欢的方面?',
  feedbackPromptMessage: '感谢提醒。请提供反馈，以便必应团队可以查看。',
  feedbackPromptGiveFeedback: '提供反馈',
  feedbackPromptGiveFeedbackAriaLabel: '提供反馈',
  feedbackPromptReportAConcern: '报告问题',
  feedbackPromptPositive: '很高兴你喜欢这个答案！',
  feedbackFormTitleText: '为什么这不起作用？',
  feedbackFormInputDefaultText: '在此处添加更多详细信息。为了帮助保护你的隐私，请不要填入你的姓名或电子邮件地址等个人信息。',
  feedbackFormLegalText: '是否有法律或政策问题？',
  feedbackFormReportAConcern: '报告问题',
  feedbackFormNotificationTitleText: '反馈已提交',
  feedbackFormNotificationBodyText: '感谢你帮助必应改进！',
  serpFeedbackFormTitleText: '请帮助我们改进体验',
  serpFeedbackFormInputDefaultText: '在此处输入反馈。为了帮助保护你的隐私，请不要填入你的姓名或电子邮件地址等个人信息。',
  serpFeedbackFormScreenshot: '包括此屏幕截图',
  submit: '提交',
  metaInternalSearchQuery: '正在搜索: `{0}`',
  metaInternalLoaderMessage: '正在为你生成答案...',
  compliantMetaInternalLoaderMessage: '从 {0} 生成安全答案',
  messageSharedContent: '共享内容',
  clickToView: '单击以查看',
  more: '更多',
  expand: '展开',
  welcomeTertiaryTitleText: '使用 AI 的强大功能从 Web 中查找答案、创建书面内容等。',
  actionBarTextInputAriaLabel: '询问必应',
  seeMore: '查看更多',
  seeLess: '查看更少',
  raiSuggestions: '这是什么?',
  actionBarStopStreamingAriaLabel: '停止流式传输',
  actionBarTextInputModeButtonAriaLabel: '文本输入模式',
  actionBarSpeechInputModeButtonAriaLabel: '启用语音输入模式',
  actionBarSubmitButtonAriaLabel: '提交',
  actionBarCancelSpeechInputButtonAriaLabel: '取消语音输入/读出',
  actionBarEditModeButtonAriaLabel: '编辑模式',
  actionBarSpeechBtnStartListeningAriaLabel: '开始聆听',
  actionBarSpeechBtnStopListeningAriaLabel: '停止侦听',
  actionBarSpeechBtnStopReadoutAriaLabel: '停止读出',
  feedbackLikeButtonAriaLabel: '点赞',
  feedbackDislikeButtonAriaLabel: '取消点赞',
  feedbackOffensiveButtonAriaLabel: '标记为冒犯性',
  feedbackCopyButtonAriaLabel: '复制',
  feedbackExportButtonAriaLabel: '导出',
  feedbackExportPdfButtonAriaLabel: 'PDF',
  feedbackExportTextButtonAriaLabel: 'Text',
  feedbackExportWordButtonAriaLabel: 'Word',
  feedbackShareButtonAriaLabel: '共享',
  messageSentAriaLabelPrefix: '已发送电子邮件',
  messageReceivedAriaLabelPrefix: '已收到消息',
  messageAttributionsCollapseBtnAriaLabel: '折叠',
  newTopicGreet1: '谢谢你帮我理清头绪! 我现在能帮你做什么?',
  newTopicGreet2: '谢谢你! 知道你什么时候准备好继续前进总是很有帮助的。我现在能为你回答什么问题?',
  newTopicGreet3: '重新开始总是很棒。问我任何问题!',
  newTopicGreet4: '当然，我很乐意重新开始。我现在可以为你提供哪些帮助?',
  newTopicGreet5: '好了，我已经为新的对话重置了我的大脑。你现在想聊些什么?',
  newTopicGreet6: '没问题，很高兴你喜欢上一次对话。让我们转到一个新主题。你想要了解有关哪些内容的详细信息?',
  newTopicGreet7: '当然，我已准备好进行新的挑战。我现在可以为你做什么?',
  newTopicGreet8: '好的，我已清理好板子，可以重新开始了。我可以帮助你探索什么?',
  newTopicGreet9: '明白了，我已经抹去了过去，专注于现在。我们现在应该探索什么?',
  newTopicGreet10: '很好，让我们来更改主题。你在想什么?',
  newTopicGreet11: '好了，我已经为新的对话擦拭干净板子了。现在我可以和你聊些什么呢?',
  newTopicGreet12: '不用担心，我很高兴尝试一些新内容。我现在可以为你回答什么问题?',
  newTopicSugg1: '教我一个新单词',
  newTopicSugg2: '如何设定可实现的目标?',
  newTopicSugg3: '教我有关登月的信息',
  newTopicSugg4: '世界上最小的哺乳动物是什么?',
  newTopicSugg5: '最深的海洋是哪个?',
  newTopicSugg6: '一年有多少小时?',
  newTopicSugg7: '我想学习一项新技能',
  newTopicSugg8: '让我大笑',
  newTopicSugg9: '有什么新闻?',
  newTopicSugg10: '给我看鼓舞人心的名言',
  newTopicSugg11: '给我说个笑话',
  newTopicSugg12: '我需要有关家庭作业的帮助',
  newTopicSugg13: '寻找非虚构作品',
  newTopicSugg14: '激励我!',
  newTopicSugg15: '向我显示食谱',
  newTopicSugg16: '如何创建预算?',
  newTopicSugg17: '教我一个新单词',
  newTopicSugg18: '天气如何?',
  newTopicSugg19: '我想学习一项新技能',
  newTopicSugg20: '宇宙是如何开始的?',
  newTopicSugg21: '为什么人类需要睡眠?',
  newTopicSugg22: '如何制作蛋糕?',
  newTopicSugg23: '火烈鸟为何为粉色?',
  newTopicSugg24: '全息影像的工作原理是什么?',
  newTopicSugg25: '金字塔是如何建成的?',
  newUserGreet: '你好，我是必应。我利用 AI 的力量来帮助你探索网络，学习新事物，并享受美好时光。我还可以生成各种内容，如散文、歌曲、代码等。你今天想做什么?',
  newUserSugg1: '搜索视频',
  newUserSugg2: '玩小游戏',
  newUserSugg3: '搜索网页',
  repeatUserGreet: '你好。很高兴再次与你聊天。你今天想研究什么有趣的事物?',
  repeatUserSugg1: '向我展示一首诗',
  repeatUserSugg2: '玩井字游戏',
  repeatUserSugg3: '谁创建了你?',
  creativeGreet: '好吧!这就是创造力。我能帮什么忙？',
  balancedGreet: '听起来不错，我们可以在趣事和事实中寻找平衡。如何提供帮助？',
  preciseGreet: '你好，我在这里帮你查答案。你有哪些问题？',
  creativeSugg1: '告诉我的星座',
  creativeSugg2: '告诉我一个关于小狗的故事',
  creativeSugg3: '你知道一切吗？',
  balancedSugg1: '为我提供有关新爱好的想法',
  balancedSugg2: '我需要一些建议',
  balancedSugg3: '哪种花最香？',
  preciseSugg1: '我需要帮助做研究',
  preciseSugg2: '为我编辑内容',
  preciseSugg3: '跟我说说第 22 任总统',
  close: '关闭',
  newTopicPrompt: '通过新主题，可以开始与必应就任何主题进行全新对话',
  typingIndicatorStopRespondingAriaLabel: '停止响应',
  welcomeLearnSegment0: '必应由 AI 提供支持，因此可能出现意外和错误。请确保核对事实，并',
  welcomeLearnSegment1: '让我们一起学习。必应由 AI 提供支持，因此可能出现意外和错误。请确保核对事实，并 ',
  welcomeLearnSegment2: '共享反馈 ',
  welcomeLearnSegment3: '以便我们可以学习和改进!',
  welcomeLearnMessage: '让我们一起学习。必应由 AI 提供支持，因此可能出现意外和错误。请确保核对事实，并 {0} 以便我们可以学习和改进！',
  welcomeLearnFeedbackSubstitue: '共享反馈',
  actionBarSuspendConvPlaceHolder: '已为挂起的帐户禁用消息传递',
  notiReConnect: '出错了。',
  notiChatEnd: '聊天主题已结束。',
  notiRestartChat: '在 {0} 小时内开始新主题',
  notificationAttemptingToReconnect: '正在尝试重新连接...',
  notificationProcessing: '正在尝试连接，请稍候',
  notificationLostConnection: '很抱歉，你的连接似乎已断开。',
  notificationLostConnectionCta: '是否要尝试重新连接？',
  sydneySapphireCopyToClipboardText: '已复制到剪贴板。',
  sydneySapphireUpsellContent: '现在就获取使用新 AI 驱动的必应应用程序吧!',
  sydneySapphireWelcomeText: '欢迎回来! 下面是此页面的一些内容。',
  sydneySapphireConsentTitleText: '使用新必应提升浏览',
  sydneySapphireConsentMessageText: '允许 Microsoft 访问你的浏览器 Web 内容，以便使用 AI 生成的摘要和新必应的热点功能更好地个性化你的体验。了解更多信息',
  sydneySapphireConsentConfirmText: '确认',
  sydneySapphireConsentDenyText: '拒绝',
  typingIndicatorStopStreamingAriaLabel: '停止流式传输',
  sydneyCarouselCollapse: '折叠',
  sydneyCarouselTitle: '最近的聊天主题',
  messageActionsCopy: '复制',
  messageActionsCopying: '正在复制',
  messageActionsCopied: '已复制',
  messageActionsCopyError: '错误',
  messageActionsExportPdf: 'PDF',
  messageActionsExportText: 'Text',
  messageActionsExportWord: 'Word',
  messageActionsReport: '报告',
  tooltipPositive: '点赞',
  tooltipNegative: '取消点赞',
  tooltipShare: '共享',
  tooltipExport: '导出',
  tooltipMore: '更多',
  tooltipSendToPhone: '在手机上继续',
  mobileUpsellMessage1: '扫描此 QR 码以在移动必应应用上继续此对话',
  mobileUpsellTitle1: '在手机上继续',
  sydneySapphireUpsellConsentTitle: '是否继续从桌面聊天?',
  sydneySapphireUpsellConsentMessage: '你在其他设备上有一个活动的必应聊天。是否要继续此对话?',
  sydneySapphireUpsellConsentConfirm: '是',
  sydneySapphireUpsellConsentDeny: '不，谢谢',
  actionBarAutoSuggestTab: '选项卡',
  actionBarAutoSuggestTap: '点击',
  actionBarKeyboardHint: '输入',
  feedbackShareAnswer: '查看此必应答案',
  feedbackShareGenerated: '查看我使用必应生成的内容',
  feedbackShareTitleFormat: '{0} | {1}',
  serpfeedback: '反馈',
  shareConversation: '共享整个对话',
  speechAuthenticationError: '身份验证失败。请稍后重试。',
  speechUnknownError: '出错了。',
  refresh: '刷新',
  feedbackShareContent: '下面是我使用新的必应（全球首个 AI支持的应答引擎）生成的答案。单击可查看完整答案，然后请你也来试一试。',
  preview: '预览',
  toneSelectorDescription: '选择对话样式',
  toneSelectorCreative: '有创造力',
  toneSelectorCreativeModifier: '更',
  toneSelectorBalanced: '平衡',
  toneSelectorBalancedModifier: '更',
  toneSelectorPrecise: '精确',
  toneSelectorPreciseModifier: '更',
  toneSelectorMoreCreative: '更\\r\\n有创造力',
  toneSelectorMoreBalanced: '更\\r\\n平衡',
  toneSelectorMorePrecise: '更\\r\\n精确',
  notificationMaxTurnsPerDay: '很抱歉，你已达到可在 24 小时内发送到必应的邮件限制。请稍后回来查看!',
  notificationMaxTurnsPerConversation: '很抱歉，此对话已达到其限制。使用“扫除”按钮清除此内容并进行更多聊天。',
  notificationMaxTurnsForMuidUsers: '你已达到今天的对话限制。',
  notificationUnauthorizedMuidUsersCta: '登录以继续你的聊天。',
  notificationChatEnterMuidUsers: '登录以提出更多问题并进行更长的对话。',
  muidUsersTermsCond1: '通过单击“开始使用”，并继续与必应交互，即表示你接受',
  muidUsersTermsCond2: '并确认你已查看',
  muidUserGetStartedText: '开始使用',
  welcomeMobSugg1: '必应如何使用 AI?',
  welcomeMobSugg2: '必应还可以做什么？',
  welcomeMobSugg3: '科技领域的最新消息是什么？',
  of: '共',
  notificationResetConversation: '很抱歉，似乎出现错误。',
  notificationResetConversationCta: '让我们重新开始吧。',
  toneSelectorCreativeTooltip: '清除对话并开始原创和富有想象力的聊天',
  toneSelectorBalancedTooltip: '清除对话并开始一个信息丰富且友好的聊天',
  toneSelectorPreciseTooltip: '清除对话并开始简洁直截了当的聊天',
  toneSelectorSuppressedTooltip: '暂时不可用。请稍后再试!',
  notificationDisengaged: '也许该换个新话题了。',
  notificationDisengagedCta: '',
  notificationForbidden: '很抱歉，你似乎不再有权访问此功能。请几天后再次查看。',
  notificationTooManyRequests: '很抱歉，现在需求量非常大。请稍后重试。',
  notificationUnauthorized: '很抱歉，你似乎已注销。',
  notificationUnauthorizedCta: '请重新登录。',
  notificationMessageError: '上一条消息似乎已中断。',
  notificationSharedTip: '此对话\u003cstrong\u003e“{0}”\u003c/strong\u003e已于 {1} 与你共享',
  mmAnswerPrompt1: '我总算给你找到了一些东西! 看一看。',
  mmAnswerPrompt2: '我终于找到了一些东西! 这是你要找的吗?',
  mmAnswerPrompt3: '抱歉搞混了，我确实给你找到了一些东西。给你!',
  mmAnswerPrompt4: '嘿! 我确实找到了一些东西，这是你想要的吗?',
  mmAnswerPrompt5: '看! 我找到了一些适合你的内容。',
  mmAnswerPrompt6: '等等，在这里! 抱歉弄乱了，看一下吧。',
  mmAnswerPrompt7: '我找到你要的媒体了! 抱歉耽搁了。',
  signInCta: '登录 ',
  signInDescription: ' 以提出更多问题并进行更长的对话',
  exportSuccessToastTitle: '已导出文件。某些格式和图像可能无法导出。',
  exportLoadingToastTitle: '导出中...',
  exportedFileUserTitle: '用户',
  exportedFileBotTitle: '必应',
  copyCodeSuccessToastTitle: '已复制到剪贴板',
  copyCodeButtonTooltip: '复制',
  threadsSharedOnDate: '于 {0} 共享',
  threadsMore: '更多',
  threadsExportPanelTitle: '选择格式',
  threadsExportPanelAriaLabel: '选择',
  threadsAADMSARedirectConfirm: '切换配置文件',
  threadsAADMSARedirectDescription:
    '您的对话历史记录正在与您的Microsoft账户一起保存。下次您使用个人账户登录时，它将保留在这里供您使用。',
  threadsCancel: '取消',
  threadsChatHistory: '聊天记录',
  threadsConfirm: '确认',
  threadsDaysAgo: '{0} 天前',
  threadsDefaultChatName: '无标题的聊天',
  threadsDelete: '删除',
  threadsDescription: '你的必应 AI 支持的 copilot 现可自动保存聊天功能。可以从任何设备、桌面或移动设备访问聊天，并无缝恢复。',
  threadsDescriptionNote: '请注意，除非专门保存，否则所有聊天将在 90 天内自动删除。',
  threadsEdit: '重命名',
  threadsLoad: '加载聊天',
  threadsMinimizeRecent: '最小化最近的聊天',
  threadsMinimizeSaved: '最小化保存的聊天',
  threadsPreview: '预览',
  threadsPreviewText: '跳回最近聊天',
  threadsRecentTitle: '聊天记录',
  threadsSavedTitle: '已保存',
  threadsSeeAllRecent: '查看所有最近的聊天',
  threadsSeeAllSaved: '查看所有保存的聊天',
  threadsTitle: '聊天',
  threadsYesterday: '昨天',
  threads2TLastAccessed: '上次访问时间',
  threads2TInfoChanged: '信息可能已更改',
  threads2TRerenderDesc: '单击“重新加载”以显示来自 Web 的最新信息',
  threads2TRerender: '重新加载',
  webPageContextPrefix: '已访问网站',
  zeroInputSuggestionFallback1: '哪款咖啡研磨机评价最好？',
  zeroInputSuggestionFallback2: '对于一个预算有限的六口之家来说，会首选哪三款车型？',
  zeroInputSuggestionFallback3: '写一个我的同事会觉得有趣的笑话',
  zeroInputSuggestionFallback4: '下一流行趋势是什么？我应该在哪里购物可以找到它？',
  zeroInputSuggestionFallback5: '撰写关于鱼和青蛙寻找爱的原创寓言故事',
  zeroInputSuggestionFallback6: '创建一个表，帮助我计划接下来两周的就餐',
  zeroInputSuggestionFallback7: '为具有讽刺风格的新社交媒体平台创建一个口号',
  zeroInputSuggestionCategory1: '商店',
  zeroInputSuggestionCategory2: '比较',
  zeroInputSuggestionCategory3: '大笑',
  zeroInputSuggestionCategory4: '聊天',
  zeroInputSuggestionCategory5: '写入',
  zeroInputSuggestionCategory6: '组织',
  zeroInputSuggestionCategory7: '创建',
};
function parseQueryParamsFromQuery(n, t) {
  var u, f, e, o;
  t === void 0 && (t = !0);
  var r = [],
    s = n && n.length > 0 ? n.split('&') : [],
    h = s.length,
    i = null;
  for (u = 0; u < h; u++)
    (f = s[u]), (e = f.indexOf('=')), e > 0 && ((i = f.substr(0, e)), i.charAt(0) == '?' && (i = i.substr(1)), i && ((i = i.toLowerCase()), (r[i] = f.substr(e + 1))));
  return t && ((o = r.first), (r.first = null == o || o == '0' ? 1 : parseInt(o))), r;
}
function parseQueryParams() {
  var n = '';
  return (
    (n = typeof Bing != 'undefined' && Bing.Url && Bing.Location ? Bing.Url.getQueryString(Bing.Location.get()) : _w.location.search.substring(1)), parseQueryParamsFromQuery(n)
  );
}
function convertQueryParamsToUrlStr(n, t) {
  t === void 0 && (t = null);
  var i = t ? t : _w.location.pathname.replace(/^\/+/, '/');
  return i + '?' + queryParamsToString(n);
}
function queryParamsToString(n) {
  for (var e, o, r, u, s, f, t = [], i = 1; i < arguments.length; i++) t[i - 1] = arguments[i];
  if (((e = []), (u = t.length), u == 0)) for (s in n) n.hasOwnProperty(s) && (t.push(s), u++);
  for (f = 0; f < u; f++) (o = t[f]), (r = n[o]), (r || r === 0) && e.push(o + '=' + r);
  return e.join('&');
}
function getCurrentQuery() {
  if (!currentQuery) {
    var n = parseQueryParams();
    currentQuery = n.q;
  }
  return currentQuery;
}
function extractDomainFromUrl(n, t, i) {
  var r, u, f, e;
  return typeof n != 'string'
    ? null
    : ((r = n),
      (u = r.indexOf('://')),
      u >= 0 && !t && ((r = r.substr(u + 3)), (u = -1)),
      (u = u >= 0 ? u + 3 : 0),
      (f = r.indexOf(':', u)),
      f >= 0 && (r = r.substr(0, f)),
      (f = r.indexOf('/', u)),
      f >= 0 && (r = r.substr(0, f)),
      (e = i ? r.indexOf('www.') : -1),
      e >= 0 && (r = r.substr(u + 4)),
      r);
}
function addCommonPersistedParams(n) {
  var i = parseQueryParams(),
    t = queryParamsToString(
      i,
      'atlahostname',
      'cdghostname',
      'thhostname',
      'testhooks',
      'adlt',
      'akamaithumb',
      'safesearch',
      'perf',
      'mockimages',
      'mobile',
      'anid',
      'isuserauth',
      'uncrunched',
      'clientid',
      'currentdate',
      'iss'
    ),
    r = n.indexOf('?') === -1 ? '?' : '&';
  return (t = t.length > 0 ? r + t : ''), n + t;
}
var currentQuery = null;
var fab_config = { fabStyle: 1, fabSbAction: 'FocusSearchBox', fabSbActionHover: 'None', fabSbActionData: 'None', fabTooltip: '', micFabAlwaysVisible: false, fabClickNoAS: true };
sj_be(
  _w,
  'click',
  function () {
    _G.UIWP = true;
  },
  1
);
