/* eslint-disable */
_w['_sydPayWallConfig'] = {
  loadSydneyConvResWithPayWall: false,
  useSydneyPayWall: false,
};
_w['_sydConvConfig'] = {
  usePill: true,
  enableSydTigerAns: true,
  enableTigerEnhancedPrompt: false,
  tigerEnhancedPromptTemplate:
    'Search for {0}. Impress me with a great response that helps me complete my most likely intent while showing the smartness, depth, and beauty (bolding, tables, and citations) you can produce. Satisfy my intent as early as possible in the response.',
  enableDlBing: false,
  // 不可滚动出聊天
  enableScrollOut: false,
  enableSydContext: true,
  enableClearConv: false,
  disableSydGhosting: false,
  isSydCorpnet: false,
  enableSydHistory: false,
  hideSydFSC: false,
  sydOptionSets: 'uprofgen,uprofupd,objopinion,iycapbing,iyxapbing',
  sydBalOpts: '',
  sydCrtOpts: 'dlfp4',
  sydPrcOpts: '',
  voiceSrOptions: '',
  sydBalExtraOpts: 'saharagenconv5',
  sydCrtExtraOpts: 'clgalileo,gencontentv3',
  sydPrcExtraOpts: 'clgalileo,gencontentv3',
  sydIDs:
    'winmuid1tf,anssupltmr2,cruisecf,emsgprcf,anssupfo,tempcacheread,temptacache,blncddv3vialang70,blncddv3vialang,winlongmsg2tf,cibprior,sydtransl,ctrlconvcss,sydconfigoptc,upsellmod3,multichatkc2,kcelshttp,kcentnam,kcshowboth,0628up,626dlfp4,517opinion,0710enfed,1107ckttzs0,realestatecf,revpayaad',
  sydBaseUrl: location.origin,
  compSydBaseUrl: '',
  isCompliantSydneyEndpointEnabled: false,
  isBingChatForEnterprise: false,
  enableUserFeedbackDefaultConsent: false,
  isFeedbackEnabled: true,
  isSharingDiagnosticsEnabled: true,
  compliantSydneyFlights: '',
  useAccountLinkingForConversationLimitUpsell: false,
  includeSubstrateToken: false,
  augloopEndpoint: 'https://augloop.office.com',
  enableProdEditorEndpoint: true,
  ciqReleaseAudienceGroup: 'Production',
  enableDeterminateProgressBar: false,
  noInitOpts: false,
  overrideSydOptions: false,
  removeDeepleo: false,
  enableSydNativeIntegration: false,
  enableSydSuperAppIntegration: false,
  enableSydSuperAppNativeVoice: false,
  enableSydSuperAppNativeVoiceContinuous: false,
  enableSydSappFeedbackButton: false,
  sydneySapphireLogLevel: 5,
  enableSydSwiftKeyIntegration: false,
  enableSydMicrosoftLauncherIntegration: false,
  enableSapphireSydVoiceExp: false,
  enableSydneySapphireBridgeMocks: false,
  enableSuperAppKeyboardPopup: false,
  sydneySuperAppFeatures: '',
  getLocationDataFromHeader: '',
  sydneySwiftKeyFeatures: '',
  sydneyMicrosoftLauncherFeatures: '',
  isSappMobileOptimizedOn: false,
  enableSapphireContextRegistration: false,
  enableSapphireContextRegistrationIAB: false,
  enableEdgeMobileNativeTTS: false,
  enableSydPreloadAudioTTS: true,
  enableSydneyShareLink: false,
  sydUrlPart: '',
  compSydUrlPart: '',
  cafePathSuffixForCompliantSydney: '',
  compliantSydOptionsSets: '',
  country: 'United States',
  countryConfidence: 8,
  state: 'California',
  city: 'Los Angeles',
  cityConfidence: 0,
  zip: '90012',
  timezoneoffset: '8',
  enableTimezoneOffsetFromJS: false,
  dma: 0,
  lat: '34.0536',
  long: '-118.2427',
  language: 'Chinese (China)',
  userMailId: '123456@hotmail.com',
  userIpAddress: '',
  isMSAAuthenticated: true,
  isVisualParityRun: false,
  enableSydAjax: false,
  moveOnlySydXAnswers: true,
  enable1TCibSlot: false,
  enableSydOverlay: false,
  enableSydX1T: true,
  enableSydTestCache: false,
  hideSydMic: false,
  enableSydCarousel: true,
  fromNoResults: false,
  sydTestCacheMsg: '',
  sydTuringSuggestionsMocked: false,
  traceId: '64b2de1567464b82ac4926be6f9befda',
  extraSappOptions: '',
  extraEdgeOptions: 'eredirecturl',
  enableSydMic: false,
  carouselQueries: '',
  sydCarPropQuery: false,
  enableSydShare: false,
  enableTigerCachedAttr: false,
  enableSydCarouselHistory: false,
  enableSydCookLoc: true,
  enableSQMsg: true,
  enable161Feats: true,
  addDv3Opt: true,
  addGenContentv3Opt: false,
  hideSydReconnect: false,
  enableErrorTelemetry: true,
  enableSemSerpNoCache: false,
  checkCreatorAnsFor1T: true,
  enableSydStrictRedirect: false,
  enableAnsCardSuffix: true,
  enableSydStaticAdsLink: false,
  removeDSAT: true,
  enableShortOpt: false,
  enableSpeechExperimentalFeatures: true,
  enableSydAjaxReset: true,
  enableSydCLOC: true,
  enableCdxFeats: true,
  cdxFeats: '',
  enableSecureUpdateConversation: false,
  enableSecureSendFeedback: false,
  disableSecureUpdateConversation: false,
  disableSecureSendFeedback: false,
  enableSemSerpShare: false,
  enableShareModalDialog: true,
  enableFdbkFinalized: true,
  enableRotateDisclaimer: false,
  enableRotateWelMsg: false,
  enableDM: false,
  enableSydImageCreate: true,
  disableCibNotificationStyleUpdate: false,
  enableSecureConnect: true,
  enableToneCook: true,
  toneDefault: 'Balanced',
  balTone: 'galileo',
  crtTone: 'h3imaginative',
  prcTone: 'h3precise',
  enableSpeechChatDataAfterPhrase: false,
  enableSpeechEarconOnInput: false,
  enableTTSOnSuggestionAfterVoice: false,
  enableSimpleVoiceInput: true,
  enableSpeechDictationMode: false,
  enableAudioPreloadLimit: false,
  enableSpeechFateTTSStop: true,
  enableSpeechGetUserMedia: false,
  enableSpeechErrorHandling: true,
  enableSpeechTTSLatencyLogging: true,
  enableSpeechInputWhileRequestIsPending: false,
  enableSpeechIconDarkTheme: true,
  enableSpeechAriaLabel: true,
  enableSpeechReopenMic: false,
  enablePersistentToneSelector: false,
  enableBalDefault: true,
  enableNewTopicAutoExpand: true,
  enableTelemetryPrivacy: false,
  isAccountLinkedWithActiveAAD: false,
  enableThreadsAADMSASwitch: true,
  enableMaxTurnsPerConversation: true,
  enableMaxTurnsFromBackend: true,
  maxTurnsPerConversation: 30,
  maxTurnsPerConversationMuidUser: 5,
  maxMessageLength: 4000,
  enableSigninTurnFix: true,
  enableAmberTurnPerConversation: false,
  amberTurnPerConversation: 0,
  enableAdSlugsDesktop: false,
  disResetTT: false,
  enablePerfTrk: true,
  enableTonePerf: true,
  enableSinglePerfEventPerMessage: true,
  enableEmbeddedPerf: false,
  enableAdSlugsMobile: true,
  enableCreatorShare: false,
  enablePuidOvr: false,
  enableUnauthRedir: true,
  enableSydSafeSearch: false,
  enableFeedbackClientSideScreenshot: true,
  enableAddMobileTagToCibOnShowConv: true,
  userPriorityLevel: 999,
  enableUserPriorityLevel: false,
  enableMMAnsType: true,
  enableStreamSyntheticTextResponses: true,
  enableToneCookExpiry: false,
  syntheticStreamSpeed: 55,
  disableShareWithNoMargin: false,
  enableMobileShareAnchorBottom: true,
  disableTabletScroll: false,
  disableTabletScrollOut: false,
  disableFocusedTabletScrollOut: false,
  disableTouchDesktopScroll: false,
  disableDesktopScroll: false,
  enableSuggEndFix: false,
  enableBalancedSerp: false,
  enableAlwaysCreativeSerp: false,
  enableBalancedSerpLog: false,
  enableCreativeLandingPage: false,
  enableShareConversation: true,
  enableGetConversationAPIWithSNRProxy: true,
  enableGetSharedMessagesAPIWithSNRProxy: true,
  enableServerLogMerging: true,
  enableThreadShareWithoutRenderCardRequest: false,
  enableSuperOptionsSets: false,
  enableAutoRecoverFromInvalidSession: true,
  enableAutoRecoverFromInvalidSessionForFirstTurn: true,
  enableOneClickCopy: false,
  enableReorderCopiedTextReferences: false,
  enableCodeCopy: true,
  enableCodeBar: false,
  enableRichTextPaste: false,
  enablePasteMarkdownTable: false,
  enablePasteMath: false,
  enableInlineFeedback: true,
  enableInlineFeedbackV2: false,
  enableInlineFeedbackV21: false,
  enableSerpFeedback: true,
  enablePersistentInputText: true,
  enableFeedbackMenuOverflow: false,
  enableActionBarIMEFix: true,
  enableGhostTrailingSpaceByLanguage: false,
  shareLoadingUI: true,
  enableFeedbackInstrumentation: true,
  isSapphireClient: false,
  enableOptimizedStreaming: false,
  enableSydneySapphireUpsellMessageActions: false,
  enableSydneySapphireUpsellEndOfChat: false,
  enableSydneySapphireUpsellContinueConversation: false,
  sydneySapphireUpsellTreatment: 4,
  enableConvModeSwitchAjax: false,
  enableSetToneFromUrl: true,
  suppressKnobCreative: 0,
  suppressKnobBalanced: 0,
  suppressKnobPrecise: 0,
  convBackBtn: false,
  enableSuppressTones: false,
  enableSearchQueryForInlineAds: false,
  enableFixForInlineAdsSQ: false,
  enableDevFormOverrideForAds: false,
  codexPartnerScenario: 'SERP',
  enableMessageExport: true,
  enableFlatActionBar: true,
  codexMUIDUser: false,
  enableCodexMuidConsentTop: false,
  enableCodexMuidConsentExplicit: false,
  enableCodexMuidConsentImplicit: false,
  bypassConsentCheck: false,
  enableFixCodeXAsBug: true,
  enableChatIconClickable: false,
  enableCreatorSendQueryWhenShowConvQuery: true,
  enableCodexWinBotMessage: false,
  enableCodexWin: false,
  enableThreads: true,
  enableThreadsCF: false,
  codexWinEnableCustomGreeting: false,
  codexWinGreetingCustomString: '',
  codexWinCurrentTurn: 0,
  enableSkipContentOriginCheck: false,
  enableMobileOneClickShare: false,
  enableMobileOneClickShareV2: true,
  enableShareQuestionWithResponse: false,
  enableShareQuestionTitlePrefix: false,
  enableShareInlineAdsIframe: false,
  enableScreenshotIgnoreOnCibSerp: true,
  enableStandaloneUtility: true,
  enableShareWholeThreadMockUp: false,
  enableThreadShareLandingPage: true,
  enableShareThreadWithNoCache: true,
  enableWholeThreadPerformanceFix: false,
  enableDisposeOrphanedHosts: false,
  enablePreserveTextFormat: true,
  disable2TSearchHistory: true,
  enable2TTest: false,
  enableSydBeacon: true,
  enableShareOnHostMessage: false,
  enableSydneySapphireCameraBridge: false,
  enableVisualSearch: true,
  removeCameraInputForVisualSearch: false,
  evssid: false,
  enableVisualSubscriptionIdOverride: false,
  visualSearchSubscriptionId: '',
  enableChatCoach: '',
  suppressAlsoTryWhenEnableSydCarousel: false,
  suppressPoleRSWhenEnableSydCarousel: false,
  disablePassBotGreetingInContext: true,
  enableHoverCardOnLearnMorePills: false,
  enableThreadContextMenu: true,
  enableCloudflareCaptcha: true,
  enableInvisibleCaptchaChallenge: false,
  enableResizeObserverWithAnimationFrame: true,
  enableStartPromotion: true,
  enableKnowledgeCardImage: true,
  enableMobileKnowledgeCardOverlay: true,
  suppressPoleRecommendedSearchWhenEnableSydCarousel: false,
  enableCopyButtonInstrumented: true,
  enableWowCDSSurvey: false,
  enableMessageExportWithPlainText: true,
  enableMessageExportOnlineWord: false,
  enableMessageExportOnlineExcel: false,
  enableThreadExportOnlineWord: false,
  enableMessageExportV2: false,
  enableShorterOnlineExportSuccessToastDuration: false,
  enableDirectlyOpenExportOnlineLink: false,
  enableLoginHintForSSO: false,
  enableLimitToMsaOnlineExport: false,
  enableAdsRedirectLinkForTextMessage: false,
  enableMSAuth1stPartyApp: false,
  enableCopyHtml: false,
  enableExportPdfWithAnswerScreenshot: false,
  enableExportDocxWithAnswerScreenshot: false,
  enableGetChats: true,
  enableLibrariesSplitImport: false,
  enableExportDocxWithFormat: true,
  enableThreadSync: true,
  enableCssSplitConvModeOnClick: false,
  enableFlux3P: false,
  enablePluginsByTone: false,
  enableDelayShowConvEvent: false,
  disableWelcomeScreen: false,
  enableWelcomeScreenV2: false,
  enableChatFRE: false,
  enableChatFRE2: false,
  enableNewTables: false,
  codexTableVersion: 1,
  enableBufferMessage: false,
  enableBufferDots: false,
  enableTestDailyLimit: false,
  enableTestTurnLimit: false,
  enableWebPageContextMessages: false,
  enableCodexPluginb: false,
  enableBICHistory: true,
  enable2TScreenshot: false,
  enable2TScreenshotSnR: false,
  enableWelcomeScreenAIRolesV1ForMobile: false,
  enablePromptExtraExtensions: false,
  aiPersonaDisabledOptionsSets: '',
  enableNewAutoSuggestEndPoint: false,
  enableFixChatScopeActive: false,
  enableHideConvMode: false,
  shouldUseSydneyDynamicCIB: false,
  enableRenderCardRequestIMSearchParams: true,
  enableCodexTesthooks: false,
  flux3PPluginList: '',
  enableTypingIndicatorAnimation: false,
  typingIndicatorAnimationDuration: 1000,
  enableMessagePrivacy: false,
  disableTooltip: false,
  enableCloseShareOnClickOutside: false,
  enableSapphireFullScreenMode: false,
  enableTypingIndicatorForSerpSlotCreator: true,
  enableOnProcessingStartEvent: false,
  enableOnProcessingCompleteEvent: false,
  enableUpdateProfile: false,
  enableTypewriter: false,
  enableConfirmPromptSingleDeleteThread: false,
  enableSydneySapphireKeyboardFirst: false,
  enableSydneySapphireGPT4Treatment1: false,
  enableSydneySapphireGPT4Treatment2: false,
  enableSydneySapphireSuggestions: false,
  enableUserMessageCopy: false,
  enableDeferredImageCreatorCard: false,
  enableSaharaStream: false,
  enableFaviconsV2: false,
  enableFaviconsAutoRefresh: false,
  enableUserIpAddress: true,
  enableActionBarV2: false,
  enableLooseMessageDensity: false,
  enableTypingIndicatorAnimation: false,
  enableSuggestionItemEnterAnimation: false,
  enableKatexScroll: true,
  enableSpeechDictationBridgeMode: false,
  enableSkipContentOriginValidation: false,
  enableEmptyThreadTime: false,
  enableLinkPreviewCarousel: false,
  useFakeDataForLinkPreviewCarousel: false,
  padding2TMobile: 92,
  enablePageHeaderOverlapClamping: false,
  enableThreadShowPlugins: false,
  enableUpdateUserMessageId: true,
  enableCreativeToneIgnoreAndDefaultToBalanced: false,
  enablePreciseToneIgnoreAndDefaultToBalanced: false,
  enablePluginPanelFre: false,
  enableSapphireSerpSuggestionChipClick: false,
  enableRenderIframeCardRequest: false,
  enableBackendExportService: false,
  codexOptionsSetsList: [],
  enableSydSuperAppAnchoredScroll: false,
  enable2TQueryConfigsOnSerpLoad: false,
  isMobileHost: false,
  autoHideConvModeInterval: 300000,
};
_w['_sydThreads'] = {
  threads: [],
};
_w['_sydConvTranslation'] = {
  actionBarPlaceholder: '有问题尽管问我...（Shift + Enter = 换行，"/" 触发提示词）',
  actionBarAriaLabel: '询问必应',
  actionBarComposeButton: '新主题',
  actionBarNewChatButtonDesktop: '开始新聊天',
  actionBarNewChatButtonMobile: '新建聊天',
  actionBarOngoingConvPlaceholder: '键入消息',
  attachmentLoading: '正在加载附件',
  bufferMessage1: '我正在使用它，请稍候',
  bufferMessage2: '请稍等',
  bufferMessage3: '花点时间思考...',
  captchaTitle: '验证身份',
  captchaDescription: '若要继续，请在下图中输入字符。',
  captchaPlaceholder: '输入字符...',
  captchaPlaceholderError: '抱歉，请重试。',
  next: '下一步',
  cancel: '取消',
  feedbackAccessed: '访问时间',
  feedbackSource: '源: 与必应的对话，',
  feedbackShareConversationQuery: '什么是新版必应?',
  messageLearnMore: '了解详细信息:',
  messageReference: '参考',
  messageReferences: '引用',
  messagePrivacyLabel: '你的个人和公司数据在此聊天中受到保护',
  inputRaiLabel: '',
  letsChat: '我们聊天吧',
  pause: '暂停',
  play: '开始游戏',
  speechFailedRecognitionError: '抱歉，我无法收听你的声音，因为语音服务器已关闭，请稍后再试。',
  speechListening: '我听着呢...',
  speechLoading: '正在等待音频...',
  speechMediaNotReachableError: '很抱歉，我无法收听你的声音，因为你没有可用的麦克风。',
  speechNoPermissionError: '你需要启用麦克风，我才能听到你的声音。',
  speechAudioPlaybackError: '出错了。',
  stop: '停止',
  welcomeContainerFAQs: '常见问题解答',
  welcomeContainerPrivacyStatement: '隐私',
  welcomeContainerUseTerms: '条款',
  welcomeContainerLearnMore: '了解更多',
  welcomeMessageItemContent1: '我可以为我挑剔的只吃橙色食物的孩子做什么饭?',
  welcomeMessageItemContent2: '销量最高的 3 种宠物吸尘器有哪些优点和缺点?',
  welcomeMessageItemContent3: '以海盗的口吻写一首关于外太空鳄鱼的俳句',
  welcomeMessageItemTitle1: '🧐 提出复杂问题',
  welcomeMessageItemTitle2: '🙌获取更好的答案',
  welcomeMessageItemTitle3: '🎨 获得创意灵感',
  welcomeMessageItemLabel4: '更多创意中的新增功能：',
  warmWelcomeTitle: '欢迎使用新必应',
  warmWelcomeTitleLine2: '',
  warmWelcomeAriaLabel: '欢迎使用新必应',
  welcomeSubtitleText: '由 AI 支持的网页版 Copilot',
  workToggleDescription: '以及你的结果包括哪些内容',
  feedbackFirstMessage: '非常抱歉没有帮助到你。是否可以详细说明你不喜欢的方面?',
  feedbackPromptMessage: '感谢提醒。请提供反馈，以便必应团队可以查看。',
  feedbackPromptGiveFeedback: '提供反馈',
  feedbackPromptGiveFeedbackAriaLabel: '提供反馈',
  feedbackPromptReportAConcern: '报告问题',
  feedbackPromptPositive: '很高兴你喜欢这个答案！',
  feedbackFormTitleText: '为什么这不起作用？',
  feedbackFormInputDefaultText: '在此处添加更多详细信息。为了帮助保护你的隐私，请不要填入你的姓名或电子邮件地址等个人信息。',
  feedbackFormLegalText: '是否有法律或政策问题？',
  feedbackFormReportAConcern: '报告问题',
  feedbackFormNotificationTitleText: '反馈已提交',
  feedbackFormNotificationBodyText: '感谢你帮助必应改进！',
  feedbackFormThanksMessage: '感谢你提供的反馈!',
  feedbackFormReturnToChatMessage: '返回到聊天',
  serpFeedbackFormTitleText: '请帮助我们改进体验',
  serpFeedbackFormInputDefaultText: '在此处输入反馈。为了帮助保护你的隐私，请不要填入你的姓名或电子邮件地址等个人信息。',
  serpFeedbackFormScreenshot: '包括此屏幕截图',
  serpFeedbackFormRadioLike: '赞',
  serpFeedbackFormRadioDislike: '踩',
  serpFeedbackFormRadioConnectionIssues: '连接问题',
  serpFeedbackFormRadioSlowResponses: '响应缓慢',
  serpFeedbackFormRadioOther: '其他',
  feedbackFormUserConsentText: '将提示共享到 Copilot、从 Copilot 收到的响应，以及此交互的诊断数据?',
  feedbackFormUserConsentYesText: '是',
  feedbackFormUserConsentNoText: '否',
  compliantPositiveFeedbackFormTitleText: '向 Microsoft 提交反馈',
  compliantPositiveFeedbackQuestionText: '你喜欢哪些方面?',
  compliantPositiveFeedbackDefaultText: '请不要提供任何个人信息。',
  compliantNegativeFeedbackFormTitleText: '向 Microsoft 发送详细反馈',
  compliantNegativeFeedbackCategoryText: '该内容是',
  compliantNegativeFeedbackQuestionText: '出了什么问题?',
  compliantFeedbackThanksText: '感谢你提交关于 {0} 的反馈!',
  compliantFeedbackCategoryInaccurate: '不准确',
  compliantFeedbackCategoryOffensive: '冒犯性或不适宜',
  compliantFeedbackCategoryOther: '其他',
  submit: '提交',
  explore: '浏览',
  exploreMore: '浏览更多',
  metaInternalSearchQuery: '正在搜索: `{0}`',
  metaInternalLoaderMessage: '正在为你生成答案...',
  metaInternalImageLoaderMessage: '分析图像: 隐私模糊会隐藏必应聊天中的人脸',
  compliantMetaInternalLoaderMessage: '从 {0} 生成安全答案',
  messageSharedContent: '共享内容',
  clickToView: '单击以查看',
  more: '更多',
  expand: '展开',
  welcomeTertiaryTitleText: '使用 AI 的强大功能从 Web 中查找答案、创建书面内容等。',
  actionBarTextInputAriaLabel: '询问必应',
  seeMore: '查看更多',
  seeLess: '查看更少',
  raiSuggestions: '这是什么?',
  actionBarStopStreamingAriaLabel: '停止流式传输',
  actionBarTextInputModeButtonAriaLabel: '使用键盘',
  actionBarSpeechInputModeButtonAriaLabel: '使用麦克风',
  actionBarVisualSearchButtonTooltip: '添加图像',
  actionBarVisualSearchButtonAriaLabel: '使用图像进行搜索',
  actionBarVisualSearchCoachMarkTitle: '带图像的新必应',
  actionBarVisualSearchCoachMarkDescription: '现在你可以使用图像与必应聊天！',
  actionBarVisualSearchCoachMarkImgAlt: '视觉搜索工具提示图像',
  actionBarSubmitButtonAriaLabel: '提交',
  actionBarCancelSpeechInputButtonAriaLabel: '取消语音输入/读出',
  actionBarEditModeButtonAriaLabel: '固定',
  actionBarSpeechBtnStartListeningAriaLabel: '使用麦克风',
  actionBarSpeechBtnStopListeningAriaLabel: '停止侦听',
  actionBarSpeechBtnStopReadoutAriaLabel: '停止读出',
  feedbackLikeButtonAriaLabel: '点赞',
  feedbackDislikeButtonAriaLabel: '不喜欢',
  feedbackOffensiveButtonAriaLabel: '标记为冒犯性',
  feedbackCopyButtonAriaLabel: '复制',
  feedbackExportButtonAriaLabel: '导出',
  feedbackExportPdfButtonAriaLabel: 'PDF',
  feedbackExportTextButtonAriaLabel: 'Text',
  feedbackExportWordButtonAriaLabel: 'Word',
  feedbackShareButtonAriaLabel: '共享',
  messageSentAriaLabelPrefix: '已发送电子邮件',
  messageReceivedAriaLabelPrefix: '已收到消息',
  messageAttributionsCollapseBtnAriaLabel: '折叠',
  newTopicGreet1: '谢谢你! 知道你什么时候准备好继续前进总是很有帮助的。我现在能为你回答什么问题?',
  newTopicGreet2: '重新开始总是很棒。问我任何问题!',
  newTopicGreet3: '当然，我很乐意重新开始。我现在可以为你提供哪些帮助?',
  newTopicGreet4: '当然，我已准备好进行新的挑战。我现在可以为你做什么?',
  newTopicGreet5: '很好，让我们来更改主题。你在想什么?',
  newTopicGreet6: '不用担心，我很高兴尝试一些新内容。我现在可以为你回答什么问题?',
  newTopicGreet7: '好的，我准备好了！感谢重置。我们应该了解哪些内容？',
  newTopicGreet8: '感谢刷新！你有新的话题吗？',
  newTopicGreet9: '明白了，让我们重新开始。接下来应该讨论什么？',
  newTopicGreet10: '下一步！我可以为你做什么？',
  newTopicGreet11: '好的，我已准备好新话题。我们应该一起了解哪些内容？',
  newTopicGreet12: '明白了，请继续！感谢告诉我。我能提供什么帮助？',
  newTopicSugg1: '教我一个新单词',
  newTopicSugg2: '如何设定可实现的目标?',
  newTopicSugg3: '教我有关登月的信息',
  newTopicSugg4: '世界上最小的哺乳动物是什么?',
  newTopicSugg5: '最深的海洋是哪个?',
  newTopicSugg6: '一年有多少小时?',
  newTopicSugg7: '我想学习一项新技能',
  newTopicSugg8: '让我大笑',
  newTopicSugg9: '有什么新闻?',
  newTopicSugg10: '给我看鼓舞人心的名言',
  newTopicSugg11: '给我说个笑话',
  newTopicSugg12: '我需要有关家庭作业的帮助',
  newTopicSugg13: '寻找非虚构作品',
  newTopicSugg14: '激励我!',
  newTopicSugg15: '向我显示食谱',
  newTopicSugg16: '如何创建预算?',
  newTopicSugg17: '教我一个新单词',
  newTopicSugg18: '天气如何?',
  newTopicSugg19: '我想学习一项新技能',
  newTopicSugg20: '宇宙是如何开始的?',
  newTopicSugg21: '为什么人类需要睡眠?',
  newTopicSugg22: '如何制作蛋糕?',
  newTopicSugg23: '火烈鸟为何为粉色?',
  newTopicSugg24: '全息影像的工作原理是什么?',
  newTopicSugg25: '金字塔是如何建成的?',
  newUserGreet: '你好，我是必应。我在这里帮助你找到答案，学习新事物，并获得乐趣，所有这些都是利用 AI 的力量。你今天想做什么?',
  newUserSugg1: '搜索图片',
  newUserSugg2: '写一首歌曲',
  newUserSugg3: '告诉我一个有趣的事实',
  repeatUserGreet: '你好！很高兴’我们可以继续聊天。你今天想要探索什么？',
  repeatUserSugg1: '告诉我关于花朵的信息',
  repeatUserSugg2: '你的工作原理是什么?',
  repeatUserSugg3: '让我微笑',
  creativeGreet: '好吧!这就是创造力。我能帮什么忙？',
  balancedGreet: '好的，我们来查找答案并聊会天。我可以为你做什么？',
  preciseGreet: '你好，我来帮你查资料。首先请问我一个问题。',
  creativeSugg1: '给我出个谜语来解',
  creativeSugg2: '给雷雨写一封情书',
  creativeSugg3: '告诉我的星座',
  balancedSugg1: '我需要帮助制定计划',
  balancedSugg2: '去露营我需要什么？',
  balancedSugg3: '写一首关于爆米花的诗',
  preciseSugg1: '教我怎么解魔方',
  preciseSugg2: '是什么让地球旋转？',
  preciseSugg3: '给我列出今晚晚餐的购物清单',
  close: '关闭',
  newTopicPrompt: '通过新主题，可以开始与必应就任何主题进行全新对话',
  typingIndicatorStopRespondingAriaLabel: '停止响应',
  canceling: '正在取消',
  welcomeLearnSegment0: '必应由 AI 提供支持，因此可能出现意外和错误。请确保核对事实，并',
  welcomeLearnSegment1: '让我们一起学习。必应由 AI 提供支持，因此可能出现意外和错误。请确保核对事实，并 ',
  welcomeLearnSegment2: '共享反馈 ',
  welcomeLearnSegment3: '以便我们可以学习和改进!',
  welcomeLearnMessage: '让我们一起学习。必应由 AI 提供支持，因此可能出现意外和错误。请确保核对事实，并 {0} 以便我们可以学习和改进！',
  welcomeLearnMessage2: '必应聊天会处理你在 Windows Copilot 中输入的字词，以生成 AI 驱动的响应，并改善你在 Windows 中的体验。',
  welcomeLearnFeedbackSubstitute: '共享反馈',
  actionBarSuspendConvPlaceHolder: '已为挂起的帐户禁用消息传递',
  notiReConnect: '出错了。',
  notiChatEnd: '聊天主题已结束。',
  notiRestartChat: '在 {0} 小时内开始新主题',
  notificationAttemptingToReconnect: '正在尝试重新连接...',
  notificationProcessing: '正在尝试连接，请稍候',
  notificationLostConnection: '很抱歉，你的连接似乎已断开。',
  notificationLostConnectionCta: '是否要尝试重新连接？',
  sydneySapphireCopyToClipboardText: '已复制到剪贴板。',
  sydneySapphireUpsellContent: '现在就获取使用新 AI 驱动的必应应用程序吧!',
  sydneySapphireWelcomeText: '欢迎回来! 下面是此页面的一些内容。',
  sydneySapphireConsentTitleText: '使用新必应提升浏览',
  sydneySapphireConsentMessageText: '允许 Microsoft 访问你的浏览器 Web 内容，以便使用 AI 生成的摘要和新必应的热点功能更好地个性化你的体验。了解更多信息',
  sydneySapphireConsentConfirmText: '确认',
  sydneySapphireConsentDenyText: '拒绝',
  sydneySapphireSummarizeSuggestionShip: '汇总',
  sydneySapphireGPT4Greet: '让我们通过 GPT-4 🎉获得创意。在发挥创意的同时，响应速度可能会变慢。你是否在考虑某个主题，还是应该为其建立分支?',
  typingIndicatorStopStreamingAriaLabel: '停止流式传输',
  sydneyCarouselCollapse: '折叠',
  sydneyCarouselTitle: '最近的聊天主题',
  messageActionsCopy: '复制',
  messageActionsCopying: '正在复制',
  messageActionsCopied: '已复制',
  messageActionsCopyError: '错误',
  messageActionsExportPdf: 'PDF',
  messageActionsExportText: 'Text',
  messageActionsExportWord: 'Word',
  messageActionsReport: '报告',
  tooltipPositive: '点赞',
  tooltipNegative: '不喜欢',
  tooltipShare: '共享',
  tooltipExport: '导出',
  tooltipMore: '更多',
  tooltipSendToPhone: '在手机上继续',
  codeDisclaimer: '此代码由 AI 生成。仔细查看和使用。有关详细信息，请{0}。',
  codeDisclaimerLinkLabel: '访问我们的常见问题解答',
  mobileUpsellMessage1: '扫描此 QR 码以在移动必应应用上继续此对话',
  mobileUpsellTitle1: '在手机上继续',
  sydneySapphireUpsellConsentTitle: '是否继续从桌面聊天?',
  sydneySapphireUpsellConsentMessage: '你在其他设备上有一个活动的必应聊天。是否要继续此对话?',
  sydneySapphireUpsellConsentConfirm: '是',
  sydneySapphireUpsellConsentDeny: '不，谢谢',
  actionBarAutoSuggestTab: 'Tab',
  actionBarAutoSuggestTap: '点击',
  actionBarKeyboardHint: '输入',
  feedbackShareAnswer: '查看此必应答案',
  feedbackShareGenerated: '查看我使用必应生成的内容',
  feedbackShareTitleFormat: '{0} | {1}',
  feedbackShowTonesButtonAriaLabel: '显示所有音调',
  feedbackHideTonesButtonAriaLabel: '隐藏所有色调',
  feedbackHidePreciseToneButtonAriaLabel: '隐藏精确',
  feedbackShareErrorToast: '共享失败。',
  serpfeedback: '反馈',
  shareConversation: '共享整个对话',
  speechAuthenticationError: '身份验证失败。请稍后重试。',
  speechUnknownError: '出错了。',
  refresh: '刷新',
  feedbackShareContent: '下面是我使用新的必应（全球首个 AI支持的应答引擎）生成的答案。单击可查看完整答案，然后请你也来试一试。',
  preview: '预览',
  toneSelectorDescription: '选择对话样式',
  toneSelectorCreative: '有创造力',
  toneSelectorCreativeModifier: '更',
  toneSelectorBalanced: '平衡',
  toneSelectorBalancedModifier: '更',
  toneSelectorPrecise: '精确',
  toneSelectorPreciseModifier: '更',
  toneSelectorMoreCreative: '更\\r\\n有创造力',
  toneSelectorMoreBalanced: '更\\r\\n平衡',
  toneSelectorMorePrecise: '更\\r\\n精确',
  toneSelectorFaster: '更快',
  toneSelectorWithGPT4: '使用 GPT-4',
  notificationMaxTurnsPerDay: '很抱歉，你已达到可在 24 小时内发送到必应的邮件限制。请稍后回来查看!',
  notificationMaxTurnsPerConversation: '很抱歉，此对话已达到其限制。点击左下角“新主题”按钮清除此内容并进行新的聊天。',
  notificationMaxTurnsForMuidUsers: '你已达到今天的对话限制。',
  notificationUnauthorizedMuidUsersCta: '登录以继续你的聊天。',
  notificationChatEnterMuidUsers: '登录以提出更多问题并进行更长的对话。',
  muidUsersTermsCond1: '通过单击“开始使用”，并继续与必应交互，即表示你接受',
  muidUsersTermsCond1Inline: '通过继续与必应交互，你将接受 ',
  muidUsersTermsCond2: '并确认你已查看',
  muidUsersPrivacyStatement: '隐私声明',
  muidUsersTermsOfUse: '使用条款',
  muidUserGetStartedText: '开始使用',
  muidUserContinueText: '继续',
  welcomeMobSugg1: '必应如何使用 AI?',
  welcomeMobSugg2: '必应还可以做什么？',
  welcomeMobSugg3: '科技领域的最新消息是什么？',
  of: '共',
  notificationResetConversation: '很抱歉，似乎出现错误。',
  notificationResetConversationCta: '让我们重新开始吧。',
  toneSelectorCreativeTooltip: '清除对话并开始原创和富有想象力的聊天',
  toneSelectorBalancedTooltip: '清除对话并开始一个信息丰富且友好的聊天',
  toneSelectorPreciseTooltip: '清除对话并开始简洁直截了当的聊天',
  toneSelectorSuppressedTooltip: '暂时不可用。请稍后再试!',
  notificationDisengaged: '也许该换个新话题了。',
  notificationDisengagedCta: '',
  notificationForbidden: '很抱歉，你似乎不再有权访问此功能。请几天后再次查看。',
  notificationTooManyRequests: '很抱歉，现在需求量非常大。请稍后重试。',
  notificationUnauthorized: '很抱歉，你似乎已注销。',
  notificationUnauthorizedCta: '请重新登录。',
  notificationMessageError: '上一条消息似乎已中断。',
  notificationSharedTip: '此对话\u003cstrong\u003e“{0}”\u003c/strong\u003e已于 {1} 与你共享',
  mmAnswerPrompt1: '我总算给你找到了一些东西! 看一看。',
  mmAnswerPrompt2: '我终于找到了一些东西! 这是你要找的吗?',
  mmAnswerPrompt3: '抱歉搞混了，我确实给你找到了一些东西。给你!',
  mmAnswerPrompt4: '嘿! 我确实找到了一些东西，这是你想要的吗?',
  mmAnswerPrompt5: '看! 我找到了一些适合你的内容。',
  mmAnswerPrompt6: '等等，在这里! 抱歉弄乱了，看一下吧。',
  mmAnswerPrompt7: '我找到你要的媒体了! 抱歉耽搁了。',
  signInCta: '登录 ',
  signInDescription: ' 以提出更多问题并进行更长的对话',
  exportSuccessToastTitle: '已导出文件。某些格式和图像可能无法导出。',
  exportLoadingToastTitle: '正在导出...',
  exportErrorToastTitle: '导出失败',
  exportedFileUserTitle: '用户',
  exportedFileBotTitle: '必应',
  exportOnlineWordButtonLabel: '联机 Word',
  exportLocalWordButtonLabel: '下载',
  exportToastViewButtonLabel: '查看',
  exportTableToExcelButtonTooltip: '在浏览器中打开',
  copyCodeSuccessToastTitle: '已复制到剪贴板',
  copyCodeButtonTooltip: '复制',
  copyCodeButtonSuccessTooltip: '已复制',
  threadsSharedOnDate: '于 {0} 共享',
  threadsMore: '更多',
  threadsExportPanelTitle: '选择格式',
  threadsExportPanelAriaLabel: '选择',
  threadsAADMSARedirectConfirm: '切换用户配置',
  threadsAADMSARedirectDescription: '正在使用 Microsoft 帐户保存你的对话历史记录。下次使用个人帐户登录时，它将在此处显示。',
  threadsCancel: '取消',
  threadsChatHistory: '聊天记录',
  threadsConfirm: '确认',
  threadsDaysAgo: '{0} 天前',
  threadsDefaultChatName: '无标题的聊天',
  threadsDelete: '删除',
  threadsDescription: '你的必应 AI 支持的 copilot 现可自动保存聊天功能。可以从任何设备、桌面或移动设备访问聊天，并无缝恢复。',
  threadsDescriptionNote: '请注意，除非专门保存，否则所有聊天将在 90 天内自动删除。',
  threadsEdit: '重命名',
  threadsLoad: '加载聊天',
  threadsMinimizeRecent: '最小化最近的聊天',
  threadsMinimizeSaved: '最小化保存的聊天',
  threadsPreview: '预览',
  threadsPreviewText: '跳回最近聊天',
  threadsRecentTitle: '聊天记录',
  threadsRecentTitleShort: '最近使用',
  threadsSavedTitle: '已保存',
  threadsSeeAllRecent: '查看所有最近的聊天',
  threadsSeeAllSaved: '查看所有保存的聊天',
  threadsTitle: '聊天',
  threadsTitleForFlux: 'Menu',
  threadsYesterday: '昨天',
  threads2TLastAccessed: '上次应答时间',
  threads2TInfoChanged: '此信息可能已更改，因为',
  threads2TArchivedText: '屏幕截图',
  threads2TReloadDescription: '单击“重新加载”以显示来自 Web 的最新信息',
  threads2TFailedSearch: '请参阅最新 Bing.com',
  threads2TReload: '搜索 Bing.com',
  userPromptTitle: '就此页面进行聊天?',
  userPromptNewTopicTitle: '开始有关此页面的新聊天?',
  userPromptConfirm: '发送',
  userPromptDeny: '忽略',
  webPageContextPrefix: '已访问网站',
  useGPT4SwitchLabel: '使用 GPT-4',
  zeroInputSuggestionFallback1: '哪款咖啡研磨机评价最好？',
  zeroInputSuggestionFallback2: '对于一个预算有限的六口之家来说，会首选哪三款车型？',
  zeroInputSuggestionFallback3: '写一个我的同事会觉得有趣的笑话',
  zeroInputSuggestionFallback4: '下一流行趋势是什么？我应该在哪里购物可以找到它？',
  zeroInputSuggestionFallback5: '撰写关于鱼和青蛙寻找爱的原创寓言故事',
  zeroInputSuggestionFallback6: '创建一个表，帮助我计划接下来两周的就餐',
  zeroInputSuggestionFallback7: '为具有讽刺风格的新社交媒体平台创建一个口号',
  zeroInputSuggestionCategory1: '商店',
  zeroInputSuggestionCategory2: '比较',
  zeroInputSuggestionCategory3: '大笑',
  zeroInputSuggestionCategory4: '聊天',
  zeroInputSuggestionCategory5: '写入',
  zeroInputSuggestionCategory6: '组织',
  zeroInputSuggestionCategory7: '创建',
  discoverMessageItemTitle: '📝 一起重写文本',
  discoverMessageItemContent: '尝试从页面中选择文本以查看我们可以一起执行的操作',
  pluginTitle: '插件',
  bookNowWithOpenTable: '立即使用 OpenTable 预订',
  scrollLeft: '向左滚动',
  scrollRight: '向右滚动',
  pluginEnabledPlugin: '已启用',
  pluginEnabledNumber: '{0} / {1}',
  pluginStartNewTopic: '开始新主题',
  pluginToChangePlugin: '更改插件',
  pluginNotificationMaxExceeded: '已启用的最大插件数',
  pluginNotificationExclusive: '{0} 与 {1} 太相似。请选择一个',
  pluginTerms: '使用条款',
  pluginPrivacy: '隐私策略',
  pluginPanelFreTitle: '插件现在可用',
  pluginPanelFreTextLabel: '新建:',
  pluginPanelFreText: '打开插件，帮助你从喜欢的品牌中查找餐厅预订、航班等。',
  pluginPanelFreDismiss: '忽略',
  pluginPanelAlertTitle: '插件在“平衡”模式下不可用',
  pluginPanelAlertSubtitle: '请选择“创意”或“精确”模式，然后重试。',
  pluginLimitationTitle: '将插件与必应 AI 配合使用',
  pluginLimitationMax: '最多为任意一个对话线程选择 3 个插件。',
  pluginLimitationLock: '在选择“新建主题”进行更改之前，插件会锁定到对话中。',
  pluginShowMore: '展开',
  threadsToggleExpansion: '切换扩展',
  threadsEnabledPlugins: '已启用插件:',
  visualSearchFlyoutTitle: '添加图像',
  visualSearchGenericErrorMessage: '很抱歉 - 你的上传似乎有一次失败。请重试',
  visualSearchInvalidUrlMessage: '抱歉 - 你提供的 URL 似乎无效。请重试',
  visualSearchFlyoutInputboxAriaLabel: '粘贴图像 URL',
  visualSearchFlyoutTakePhotoButtonLabel: '拍照',
  visualSearchDragAndDropLabel: '将图片拖至此处',
  visualSearchFlyoutUploadButtonLabel: '从此设备上传',
  raiDisclaimerLabel: 'AI 生成的内容可能不正确',
  slimHeaderTitle: '查看 AI 支持的新必应的解答',
};
function parseQueryParamsFromQuery (n, t) {
  var u, f, e, o;
  t === void 0 && (t = !0);
  var r = [],
    s = n && n.length > 0 ? n.split('&') : [],
    h = s.length,
    i = null;
  for (u = 0; u < h; u++)
    (f = s[u]), (e = f.indexOf('=')), e > 0 && ((i = f.substr(0, e)), i.charAt(0) == '?' && (i = i.substr(1)), i && ((i = i.toLowerCase()), (r[i] = f.substr(e + 1))));
  return t && ((o = r.first), (r.first = null == o || o == '0' ? 1 : parseInt(o))), r;
}
function parseQueryParams () {
  var n = '';
  return (
    (n = typeof Bing != 'undefined' && Bing.Url && Bing.Location ? Bing.Url.getQueryString(Bing.Location.get()) : _w.location.search.substring(1)), parseQueryParamsFromQuery(n)
  );
}
function convertQueryParamsToUrlStr (n, t) {
  t === void 0 && (t = null);
  var i = t ? t : _w.location.pathname.replace(/^\/+/, '/');
  return i + '?' + queryParamsToString(n);
}
function queryParamsToString (n) {
  for (var e, o, r, u, s, f, t = [], i = 1; i < arguments.length; i++) t[i - 1] = arguments[i];
  if (((e = []), (u = t.length), u == 0)) for (s in n) n.hasOwnProperty(s) && (t.push(s), u++);
  for (f = 0; f < u; f++) (o = t[f]), (r = n[o]), (r || r === 0) && e.push(o + '=' + r);
  return e.join('&');
}
function getCurrentQuery () {
  if (!currentQuery) {
    var n = parseQueryParams();
    currentQuery = n.q;
  }
  return currentQuery;
}
function extractDomainFromUrl (n, t, i) {
  var r, u, f, e;
  return typeof n != 'string'
    ? null
    : ((r = n),
      (u = r.indexOf('://')),
      u >= 0 && !t && ((r = r.substr(u + 3)), (u = -1)),
      (u = u >= 0 ? u + 3 : 0),
      (f = r.indexOf(':', u)),
      f >= 0 && (r = r.substr(0, f)),
      (f = r.indexOf('/', u)),
      f >= 0 && (r = r.substr(0, f)),
      (e = i ? r.indexOf('www.') : -1),
      e >= 0 && (r = r.substr(u + 4)),
      r);
}
function addCommonPersistedParams (n) {
  var i = parseQueryParams(),
    t = queryParamsToString(
      i,
      'atlahostname',
      'cdghostname',
      'thhostname',
      'testhooks',
      'adlt',
      'akamaithumb',
      'safesearch',
      'perf',
      'mockimages',
      'mobile',
      'anid',
      'isuserauth',
      'uncrunched',
      'clientid',
      'currentdate',
      'iss'
    ),
    r = n.indexOf('?') === -1 ? '?' : '&';
  return (t = t.length > 0 ? r + t : ''), n + t;
}
var currentQuery = null;
var fab_config = {
  fabStyle: 1,
  fabSbAction: 'FocusSearchBox',
  fabSbActionHover: 'None',
  fabSbActionData: 'None',
  fabTooltip: '',
  micFabAlwaysVisible: false,
  fabClickNoAS: false,
  FabAddSuggestions: false,
  DisableAlsoTryWhenHasPoleRS: false,
};
sj_be(
  _w,
  'click',
  function () {
    _G.UIWP = true;
  },
  1
);
