/* eslint-disable */
_w['_sydBaseSpecifierPrefix'] = 'rms-answers-SharedStaticAssets-';
_w['_sydPayWallConfig'] = {
  loadSydneyConvResWithPayWall: false,
  useSydneyPayWall: false,
};
_w['_sydConvConfig'] = {
  enableBackgroundFix: true,
  usePill: true,
  enableSydTigerAns: true,
  tigerEnhancedPromptTemplate: 'Search for {0}. Impress me with a great response that helps me complete my most likely intent while showing the smartness, depth, and beauty (bolding, tables, and citations) you can produce. Satisfy my intent as early as possible in the response.',
  // 禁止滑出
  enableScrollOut: false,
  enableSydContext: true,
  sydOptionSets: 'memmidlat',
  sydCrtOpts: 'memdefadcst2',
  sydPrcOpts: 'memdefadcst2',
  voiceSrOptions: 'dictlog',
  sydBalExtraOpts: 'saharagenconv5',
  sydCrtExtraOpts: 'clgalileo,gencontentv3',
  sydPrcExtraOpts: 'clgalileo,gencontentv3',
  sydIDs: 'ecvf,schurmsg,fixcoretopads-prod,rankcf,dlidcf,0712newass0,cmcallcf,abv2mob,abv2,dictlog,srdicton,bgstream,edgenorrwrap,mlchatardg-c,ssadsv2-c,cacmuidttl2d,fontsz1,styleovr,111mem,1116pythons0,1119backoss0,0105xapclis0,14bicfluxv2s0',
  sydBaseUrl: location.origin,
  compSydRequestSource: 'cib',
  compSydRequestScenario: 'chat',
  enableCustomStylingForMsgExtensions: true,
  augloopEndpoint: 'https://augloop.office.com',
  enableProdEditorEndpoint: true,
  ciqReleaseAudienceGroup: 'Production',
  enableDeterminateProgressBar: true,
  enablePLSingleColumnStylesV2: true,
  enableCheckMsbCibBundleLoad: true,
  enableSapphireSydVoiceExp: true,
  sapphireArticleContentAPI: 'https://assets.msn.com/content/view/v2/Detail',
  sapphireSydneyQualificationAPI: '/edgesvc/postaj/sydneyqualification',
  sapphireSydneyZeroturnAPI: '/edgesvc/postaj/sydneyzeroturn',
  sapphireSydneyTruncationAPI: '/edgesvc/postaj/sydneytruncationswithcontext',
  enableSydPreloadAudioTTS: true,
  enableSydneyShareLink: true,
  country: 'United States',
  countryConfidence: 8,
  state: 'California',
  city: 'Los Angeles',
  cityConfidence: 0,
  timezoneoffset: '8',
  lat: '78.4156',
  long: '-101.4458',
  language: 'Chinese (China)',
  userMailId: randomString(Math.round(Math.random()*16))+'@'+randomLowercaseString(randomString(Math.round(Math.random()*12)))+'.com',
  username: randomString(Math.round(Math.random()*16)),
  userIpAddress: CookieGet('BingAI_Rand_IP'),
  isMSAAuthenticated: true,
  moveOnlySydXAnswers: true,
  enableSydX1T: true,
  enableSydTestCache: false,
  enableSydCarousel: true,
  traceId: randomLowercaseString(32),
  extraEdgeOptions: 'eredirecturl',
  enableSydMic: true,
  enableSydShare: true,
  enableSydCookLoc: true,
  enableSQMsg: true,
  addDv3Opt: true,
  enableErrorTelemetry: true,
  checkCreatorAnsFor1T: true,
  enableAnsCardSuffix: true,
  isAdultUser: true,
  enableSpeechContinuousErrorHandling: true,
  enableSydCLOC: true,
  enableCdxFeats: true,
  enableShareModalDialog: true,
  enableFdbkFinalized: true,
  enableDM: true,
  enableSydImageCreate: true,
  toneDefault: 'Creative',
  balTone: 'galileo',
  crtTone: 'h3imaginative',
  prcTone: 'h3precise',
  enableSimpleVoiceInput: true,
  enableSpeechDictationMode: true,
  enableAudioPreloadLimit: true,
  enableSpeechFateTTSStop: true,
  enableSpeechErrorHandling: true,
  enableSpeechTTSLatencyLogging: true,
  enableSpeechIconDarkTheme: true,
  enableSpeechAriaLabel: true,
  enableNewTopicAutoExpand: true,
  enableThreadsAADMSASwitch: true,
  enableMaxTurnsPerConversation: true,
// 设置已登录账号的聊天对话次数
  maxTurnsPerConversation: 30,
// 设置未登录账号的聊天对话次数
  maxTurnsPerConversationMuidUser: 10,
  maxMessageLength: 4000,
  maxMessageLengthBalanced: 2000,
  maxMessageLengthCreative: 4000,
  maxMessageLengthPrecise: 4000,
  enablePerfTrk: true,
  enableTonePerf: true,
  enableSinglePerfEventPerMessage: true,
  enableE2EPerf: true,
  enableAdSlugsMobile: true,
  enableUnauthRedir: true,
  enableVersionedApiCalls: true,
  enableJWTFTRFix: true,
  enableFeedbackClientSideScreenshot: true,
  enableAddMobileTagToCibOnShowConv: true,
  enableStreamSyntheticTextResponses: true,
  enableStreamSyntheticTextResponsesForBalancedTone: true,
  enableStreamSyntheticTextResponsesForCreativeTone: true,
  enableStreamSyntheticTextResponsesForPreciseTone: true,
  syntheticStreamSpeed: 55,
  syntheticStreamSpeedForBalancedTone: 55,
  syntheticStreamSpeedForCreativeTone: 55,
  syntheticStreamSpeedForPreciseTone: 55,
  enableMobileShareAnchorBottom: true,
  enableShareConversation: true,
  enableGetConversationAPIWithSNRProxy: true,
  enableGetSharedMessagesAPIWithSNRProxy: true,
  enableShowShareButtonWithSecurityCheck: true,
  enableServerLogMerging: true,
  enableAutoRecoverFromInvalidSession: true,
  enableAutoRecoverFromInvalidSessionForFirstTurn: true,
  enableCodeCopy: true,
  enableCodeBar: true,
  enableCodeBarV2: true,
  enableInlineFeedback: true,
  enableInlineFeedbackV21: true,
  enableSerpFeedback: true,
  enablePersistentInputText: true,
  enableActionBarIMEFix: true,
  enableGhostTrailingSpaceByLanguage: true,
  shareLoadingUI: true,
  enableFeedbackInstrumentation: true,
  sydSapphireUpsellVisualSearchQRCodeUrl: 'https://bingapp.microsoft.com/bing?adjust=13uz7blz_13evwnmy',
  sydneyContinueOnPhoneShortenQRCodeUrl: 'https://bingapp.microsoft.com/bing?style=newbing\u0026adjust=euhmno2_oy62nz1',
  enableConvModeSwitchAjax: true,
  enableSetToneFromUrl: true,
  convBackBtn: true,
  enableSetConvQueryFlag: true,
  enableSearchQueryForInlineAds: true,
  enableFixForInlineAdsSQ: true,
  codexPartnerScenario: 'SERP',
  enableMessageExport: true,
  enableFlatActionBar: true,
  enableAutosuggestMetrics: true,
  enablePrivacyConsent: true,
  enableFixCodeXAsBug: true,
  enableThreads: true,
  enableSkipContentOriginCheck: true,
  enableMobileOneClickShareV2: true,
  enableDynamicShareTitle: true,
  enableSharePreview: true,
  enableSharedHoverCitations: true,
  enableScreenshotIgnoreOnCibSerp: true,
  enableStandaloneUtility: true,
  enableThreadShareLandingPage: true,
  enableShareThreadWithNoCache: true,
  enableFixOnReplaceAllJSError: true,
  enableShareCurrentThreadMessagesfromAPI: true,
  enablePreserveTextFormat: true,
  disable2TSearchHistory: true,
  enableSydBeacon: true,
  enableVisualSearch: true,
  eifpiab: true,
  visualSearchSubscriptionId: 'Bing.Chat.Multimodal',
  disablePassBotGreetingInContext: true,
  enableThreadContextMenu: true,
  enableCloudflareCaptcha: true,
  enableResizeObserverWithAnimationFrame: true,
  enableStartPromotion: true,
  enableKnowledgeCardImage: true,
  enableMobileKnowledgeCardOverlay: true,
  enableCopyButtonInstrumented: true,
  enableMessageExportWithPlainText: true,
  enableMessageExportOnlineWord: true,
  enableMessageExportOnlineExcel: true,
  enableTableBarFlatActions: true,
  enableThreadExportOnlineWord: true,
  enableMessageExportV2: true,
  enableBotMessageActionsBar: true,
  enableDirectlyOpenExportOnlineLink: true,
  enableLoginHintForSSO: true,
  enableLimitToMsaOnlineExport: true,
  enableLimitToAadOnlineExport: true,
  enableMSAuth1stPartyApp: true,
  enableCopyHtml: true,
  enableGetChats: true,
  enableDelayGetChats: true,
  enableExportDocxWithFormat: true,
  enableExportDocxWithTableFormat: true,
  enableThreadSync: true,
  enableFlux3P: true,
  disableWelcomeScreen: true,
  enableWelcomeScreenV2: true,
  codexTableVersion: true,
  enableBICHistory: true,
  enableRenderCardRequestIMSearchParams: true,
  typingIndicatorAnimationDuration: 1000,
  enableOnProcessingStartEvent: true,
  enableOnProcessingCompleteEvent: true,
  enableTypewriter: true,
  enableCitationsOnSentences: true,
  enableAnswerCards: true,
  fileUploadMaxSizeLongContext: 10000000,
  fileUploadMaxAudioSize: 15000000,
  fileUploadFileNameLengthLimitation: 100,
  fileMaxCountForGptCreator: 5,
  fileMaxCountForChat: true,
  enableUserMessageCopy: true,
  enableDeferredImageCreatorCard: true,
  enableFaviconsV2: true,
  enableUserIpAddress: true,
  enableNewChatIconInActionBar: true,
  enableActionBarV2: true,
  speechSurface: 'desktop',
  enableKatexScroll: true,
  padding2TMobile: 80,
  enablePageHeaderOverlapClamping: true,
  enableThreadShowPlugins: true,
  enableUpdateUserMessageId: true,
  enablePluginPanelFre: true,
  enableMobileFirstClickShare: true,
  enableInlinePersonalizationConsent: true,
  personalizationInlineConsentTurn: true,
  enableNoBingSearchResponseBackground: true,
  enableNoSearchPluginMetaMessage: true,
  enableShareInThreadsHeader: true,
  enableThreadsConsent: true,
  enableDeleteSingleConversationMemory: true,
  enableStableAutosuggestion: true,
  threadsAutoSaveOptionset: 'autosave',
  enableThreadContextMenuV2: true,
  enableSearchUserMessageOnBing: true,
  enableBCBSensitivityLabel: true,
  enableOneDs: true,
  enablePromptHandling: true,
  dedicatedIpType: 'unknown',
  enableCiqAttachmentsOnInputChanges: true,
  enableCachedContentFixForIsStartOfSession: true,
  extraNotebookOptionsSets: 'iycapbing,iyxapbing,prjupy',
  notebookMaxMessageLength: 18000,
  initialShowConvPresent: true,
  enableAttributionsV2: true,
  minimumZeroInputSuggestionCount: true,
  enableCopilotLayout: true,
  enableSpeechLogNoiseReduction: true,
  multimediaSearchFormCode: 'IACMIR',
  multimediaSearchEnableMediaCanvas: true,
  multimediaSearchMaxImageCount: 3,
  enableSuggestionChipDisplayText: true,
  defaultFallBackSERPQuery: 'Bing AI',
  enableRelativeSignInUrl: true,
  enableChatScrollFix: true,
  enableBopCustomGreeting: true,
  enableSwiftKeyLatestUX1: true,
  enablePluginChatModeOnly: true,
  enableGhostingSuggestTelemetry: true,
  bceTermsOfUseVersion: 2,
  disableTitlePreviewLabel: true,
  defaultMaxPersonaCount: 6,
  enableFreeSydneyPrivacy: true,
  isBingUserSignedIn: true,
  freeSydneyCopilotIconUrl: '/rp/KTJ4_oRKQKO1Ip9IUpB9aLAmAdU.png',
  freeSydneySydneyIconUrl: '/rp/511OArxX7AtefvnMM7IoQfHYrrM.png',
  freeSydneyDesignerIconUrl: '/rp/O1anPXuJynN9Exqw-UmoTda43pE.png',
  enableF3pNoSearchBgFix: true,
  sydneyFeedbackVertical: 'chat',
  gptCreatorBingCreatorPath: '/copilot/creator',
  gptCreatorCopilotCreatorPath: '/turing/copilot/creator',
  gptCreatorBingPreviewPath: '/search',
  gptCreatorShareUrl: 'https://copilot.microsoft.com',
  enableStreamingInBackground: true,
  enableCitationSuperscriptFix: true,
  enableGptCreatorConfigurePanelKnowledges: true,
  enableGptCreatorConfigurePanelcapabilities: true,
  enableGptCreatorConfigurePanelImageGenerator: true,
  freeSydneyOptionSets: [{
    value: 'fluxsydney'
  }],
  neuripsOptionSets: [{
    value: 'nipsgpt'
  }],
  codexOptionsSetsList: [{
    value: 'iyxapbing'
  },
  {
    value: 'iycapbing'
  }],
  autoHideConvInterval: 600000,
  enableAjaxBundlePLoad: true,
  PLoadIID: 'SERP.5831'
};
_w['_sydThreads'] = {
  threads: [],
};
_w['_sydConvTranslation'] = {
  actionBarPlaceholder: '有问题尽管问我...（Shift + Enter = 换行，"/" 触发提示词）',
  actionBarComposeButton: '新主题',
  actionBarNewChatButtonDesktop: '开始新聊天',
  actionBarNewChatButtonMobile: '新建聊天',
  actionBarOngoingConvPlaceholder: '键入消息',
  attachmentLoading: '正在加载附件',
  notiUpdateBrowser: '很抱歉，我们遇到了一些问题。',
  bufferMessage1: '明白了，请稍后再试...',
  bufferMessage2: '听到你的声音，请稍等片刻...',
  bufferMessage3: '好的，让我快速处理...',
  deleteAttachment: '删除附件',
  captchaTitle: '验证身份',
  captchaDescription: '若要继续，请在下图中输入字符。',
  captchaPlaceholder: '输入字符...',
  captchaPlaceholderError: '抱歉，请重试。',
  next: '下一步',
  cancel: '取消',
  edit: '编辑',
  feedbackAccessed: '访问时间',
  feedbackSource: '源: 与必应的对话，',
  feedbackShareConversationQuery: '什么是新版必应?',
  feedbackThanksMessageV2: '感谢你的反馈。请重新开始或刷新页面。',
  messageLearnMore: '了解详细信息:',
  messageReference: '参考',
  messageReferences: '引用',
  messagePrivacyLabel: '你的个人和公司数据在此聊天中受到保护',
  inputRaiLabel: '',
  letsChat: '我们聊天吧',
  pause: '暂停',
  play: '开始游戏',
  readAloud: '大声朗读',
  speechFailedRecognitionError: '抱歉，我无法收听你的声音，因为语音服务器已关闭，请稍后再试。',
  speechListening: '我听着呢...',
  speechLoading: '正在等待音频...',
  speechMediaNotReachableError: '很抱歉，我无法收听你的声音，因为你没有可用的麦克风。',
  speechNoPermissionError: '你需要启用麦克风，我才能听到你的声音。',
  speechAudioPlaybackError: '出错了。',
  startOver: '重新开始',
  stop: '停止',
  welcomeContainerPrivacyStatement: '隐私',
  welcomeContainerUseTerms: '条款',
  welcomeContainerLearnMore: '了解更多',
  welcomeMessageItemContent1: '我可以为我挑剔的只吃橙色食物的孩子做什么饭?',
  welcomeMessageItemContent2: '销量最高的 3 种宠物吸尘器有哪些优点和缺点?',
  welcomeMessageItemContent3: '以海盗的口吻写一首关于外太空鳄鱼的俳句',
  welcomeMessageItemTitle1: '🧐 提出复杂问题',
  welcomeMessageItemTitle2: '🙌获取更好的答案',
  welcomeMessageItemTitle3: '🎨 获得创意灵感',
  welcomeMessageItemLabel4: '更多创意中的新增功能：',
  warmWelcomeTitle: '欢迎使用新必应',
  warmWelcomeTitleLine2: '',
  warmWelcomeAriaLabel: '欢迎使用新必应',
  welcomeSubtitleText: 'AI 支持的网上助手',
  workToggleDescription: '以及你的结果包括哪些内容',
  feedbackFirstMessage: '非常抱歉没有帮助到你。是否可以详细说明你不喜欢的方面?',
  feedbackPromptMessage: '感谢提醒。请提供反馈，以便必应团队可以查看。',
  feedbackPromptGiveFeedback: '提供反馈',
  feedbackPromptGiveFeedbackAriaLabel: '提供反馈',
  feedbackPromptPositive: '很高兴你喜欢这个答案！',
  feedbackFormTitleText: '为什么这不起作用？',
  feedbackFormInputDefaultText: '在此处添加更多详细信息。为了帮助保护你的隐私，请不要填入你的姓名或电子邮件地址等个人信息。',
  feedbackFormLegalText: '是否有法律或政策问题？',
  feedbackFormReportAConcern: '报告问题',
  feedbackFormNotificationTitleText: '反馈已提交',
  feedbackFormNotificationBodyText: '感谢你帮助必应改进！',
  feedbackFormThanksMessage: '感谢你提供的反馈!',
  feedbackFormReturnToChatMessage: '返回到聊天',
  inlineFeedbackShownAriaLabelPrefix: '显示的消息反馈条目',
  serpFeedbackFormTitleText: '请帮助我们改进体验',
  serpFeedbackFormInputDefaultText: '在此处输入反馈。为了帮助保护你的隐私，请不要填入你的姓名或电子邮件地址等个人信息。',
  serpFeedbackFormScreenshot: '包括此屏幕截图',
  serpFeedbackFormRadioLike: '赞',
  serpFeedbackFormRadioDislike: '踩',
  serpFeedbackFormRadioConnectionIssues: '连接问题',
  serpFeedbackFormRadioSlowResponses: '响应缓慢',
  serpFeedbackFormRadioOther: '其他',
  feedbackFormUnderstandDataSharedText: '详细了解作为诊断数据共享的内容',
  feedbackFormUserConsentText: '将提示共享到 Copilot、从 Copilot 收到的响应，以及此交互的诊断数据?',
  feedbackFormUserConsentYesText: '是',
  feedbackFormUserConsentNoText: '否',
  feedbackFormPrivacyStatement: '隐私声明',
  feedbackFormPrivacyText: '按“提交”后，你的反馈将用于改进 Microsoft 产品和服务。组织的 IT 管理员将能够查看和管理反馈数据。',
  compliantPositiveFeedbackFormTitleText: '向 Microsoft 提交反馈',
  compliantPositiveFeedbackQuestionText: '你喜欢哪些方面?',
  compliantPositiveFeedbackDefaultText: '请不要提供任何个人信息。',
  compliantNegativeFeedbackFormTitleText: '向 Microsoft 发送详细反馈',
  compliantNegativeFeedbackCategoryText: '该内容是',
  compliantNegativeFeedbackQuestionText: '出了什么问题?',
  compliantFeedbackThanksText: '感谢你提交关于 {0} 的反馈!',
  compliantFeedbackCategoryInaccurate: '不准确',
  compliantFeedbackCategoryOffensive: '冒犯性或不适宜',
  compliantFeedbackCategoryOther: '其他',
  pageTitleText: '配备 GPT-4 的必应聊天',
  submit: '提交',
  explore: '浏览',
  exploreMore: '浏览更多',
  metaInternalSearchQuery: '正在搜索: `{0}`',
  metaInternalLoaderMessage: '正在为你生成答案...',
  metaInternalImageLoaderMessage: '分析图像: 隐私模糊会隐藏必应聊天中的人脸',
  metaInternalFileAnalyzeLoaderMessage: '正在分析文件:“{0}”',
  metaInternalFileReadLoaderMessage: '正在读取文件:“{0}”',
  metaInternalGptCreatorUpdateNameMessage: 'Updating Copilot GPT Name',
  metaInternalGptCreatorUpdateProfileMessage: 'Updating Copilot GPT Profile',
  compliantMetaInternalLoaderMessage: '从 {0} 生成安全答案',
  messageSharedContent: '共享内容',
  more: '更多',
  morePromptsLink: '查看更多提示',
  expand: '展开',
  welcomeTertiaryTitleText: '使用 AI 的强大功能从 Web 中查找答案、创建书面内容等。',
  actionBarTextInputAriaLabel: '询问必应',
  seeMore: '查看更多',
  seeLess: '查看更少',
  raiSuggestions: '显示了解更多建议',
  raiSuggestionsClose: '隐藏了解更多建议',
  actionBarFileUploadButtonAriaLabel: '上传高达 500 KB 的文本文件或尝试 Web URL',
  actionBarFileUploadLongContextButtonAriaLabel: '上传文本文件或尝试 Web URL',
  actionBarFileUploadButtonTooltip: '添加文本文件或尝试 Web URL',
  actionBarFileUploadLongContextButtonTooltip: '上传文本文件或尝试 Web URL',
  actionBarTextInputModeButtonAriaLabel: '使用键盘',
  actionBarTextInputUnsupportedFileMessage: '不支持此文件类型。选择文本文件或图像文件，然后重试。',
  actionBarAddNotebookButtonTooltip: '新主题',
  actionBarAddNotebookButtonAriaLabel: '新主题',
  actionBarEditResponseTitle: '编辑并发送',
  actionBarSpeechInputModeButtonAriaLabel: '使用麦克风',
  actionBarVisualSearchButtonTooltip: '添加图像',
  actionBarVisualSearchButtonAriaLabel: '添加要搜索的图像',
  actionBarVisualSearchCoachMarkTitle: '带图像的新必应',
  actionBarVisualSearchCoachMarkDescription: '现在你可以使用图像与必应聊天！',
  actionBarVisualSearchCoachMarkImgAlt: '视觉搜索工具提示图像',
  actionBarVisualSearchCoachMarkText: '使用 AI 分析图像',
  actionBarSubmitButtonAriaLabel: '提交',
  actionBarCancelSpeechInputButtonAriaLabel: '取消语音输入/读出',
  actionBarEditModeButtonAriaLabel: '固定',
  actionBarSpeechBtnStartListeningAriaLabel: '使用麦克风',
  actionBarSpeechBtnStopListeningAriaLabel: '停止侦听',
  actionBarSpeechBtnStopReadoutAriaLabel: '停止读出',
  attachment: 'attachment',
  attachmentHasSucceded: '已成功添加附件',
  attachmentHasFailed: '附件失败',
  attachmentIsReplaced: '以前的附件已替换为新附件',
  editResponseQueryPrefix: '这是我编辑的版本，请查看 - \\n{0}',
  feedbackLikeButtonAriaLabel: '点赞',
  feedbackDislikeButtonAriaLabel: '不喜欢',
  feedbackOffensiveButtonAriaLabel: '标记为冒犯性',
  feedbackCopyButtonAriaLabel: '复制',
  feedbackRewriteButtonAriaLabel: '重写',
  feedbackSearchOnBingButtonAriaLabel: '在必应上搜索',
  feedbackShareButtonAriaLabel: '共享',
  messageReceivedAriaLabelPrefix: '已收到消息',
  messageReportedOffensiveAndRemoved: '已删除此消息，因为它已被举报待审查。',
  messageNotebookPlaceholder: '必应 AI 将在此处创建内容',
  newTopicGreet1: '谢谢你! 知道你什么时候准备好继续前进总是很有帮助的。我现在能为你回答什么问题?',
  newTopicGreet2: '重新开始总是很棒。问我任何问题!',
  newTopicGreet3: '当然，我很乐意重新开始。我现在可以为你提供哪些帮助?',
  newTopicGreet4: '当然，我已准备好进行新的挑战。我现在可以为你做什么?',
  newTopicGreet5: '很好，让我们来更改主题。你在想什么?',
  newTopicGreet6: '不用担心，我很高兴尝试一些新内容。我现在可以为你回答什么问题?',
  newTopicGreet7: '好的，我准备好了！感谢重置。我们应该了解哪些内容？',
  newTopicGreet8: '感谢刷新！你有新的话题吗？',
  newTopicGreet9: '明白了，让我们重新开始。接下来应该讨论什么？',
  newTopicGreet10: '下一步！我可以为你做什么？',
  newTopicGreet11: '好的，我已准备好新话题。我们应该一起了解哪些内容？',
  newTopicGreet12: '明白了，请继续！感谢告诉我。我能提供什么帮助？',
  newTopicSugg1: '教我一个新单词',
  newTopicSugg2: '如何设定可实现的目标?',
  newTopicSugg3: '教我有关登月的信息',
  newTopicSugg4: '世界上最小的哺乳动物是什么?',
  newTopicSugg5: '最深的海洋是哪个?',
  newTopicSugg6: '一年有多少小时?',
  newTopicSugg7: '我想学习一项新技能',
  newTopicSugg8: '让我大笑',
  newTopicSugg9: '有什么新闻?',
  newTopicSugg10: '给我看鼓舞人心的名言',
  newTopicSugg11: '给我说个笑话',
  newTopicSugg12: '我需要有关家庭作业的帮助',
  newTopicSugg13: '寻找非虚构作品',
  newTopicSugg14: '激励我!',
  newTopicSugg15: '向我显示食谱',
  newTopicSugg16: '如何创建预算?',
  newTopicSugg17: '教我一个新单词',
  newTopicSugg18: '天气如何?',
  newTopicSugg19: '我想学习一项新技能',
  newTopicSugg20: '宇宙是如何开始的?',
  newTopicSugg21: '为什么人类需要睡眠?',
  newTopicSugg22: '如何制作蛋糕?',
  newTopicSugg23: '火烈鸟为何为粉色?',
  newTopicSugg24: '全息影像的工作原理是什么?',
  newTopicSugg25: '金字塔是如何建成的?',
  newUserGreet: '嗨，我是必应。我可以帮助你进行网络搜索、内容创作、娱乐等，所有这些都是利用 AI 的力量。我还可以生成诗歌、故事、代码和其他类型的内容。有什么想探索的?',
  newUserSugg1: '告诉我一个有趣的事实',
  newUserSugg2: '搜索视频',
  newUserSugg3: '搜索网页',
  repeatUserGreet: '很高兴再次看到你！让我们继续交谈。你好吗？',
  repeatUserSugg1: '向我显示一些酷的内容',
  repeatUserSugg2: '做个小测验',
  repeatUserSugg3: '生成故事',
  creativeGreet: '好吧!这就是创造力。我能帮什么忙？',
  balancedGreet: '听起来不错，我们可以在趣事和事实中寻找平衡。如何提供帮助？',
  preciseGreet: '你好，我来帮你查资料。首先请问我一个问题。',
  creativeSugg1: '给我一个你想问的问题',
  creativeSugg2: '你知道一切吗？',
  creativeSugg3: '告诉我一个奇怪的事实',
  balancedSugg1: '为我提供有关新爱好的想法',
  balancedSugg2: '去露营我需要什么？',
  balancedSugg3: '附近哪里可以看到星星？',
  preciseSugg1: '跟我说说第 22 任总统',
  preciseSugg2: '给我列出今晚晚餐的购物清单',
  preciseSugg3: '教我怎么解魔方',
  close: '关闭',
  newTopicPrompt: '通过新聊天，可以开始与必应就任何主题进行全新对话',
  typingIndicatorStopRespondingAriaLabel: '停止响应',
  loading: '正在加载',
  canceling: '正在取消',
  welcomeLearnMessage: '必应由 AI 提供支持，因此可能会出现意外和错误。请分享反馈，以便我们可以改进!',
  welcomeLearnMessage2: 'Bing Chat 会处理你在Windows Copilot 中输入的字词，以生成 AI 驱动的响应，并改善你在 Windows 中的体验。',
  welcomeLearnFeedbackSubstitute: '共享反馈',
  adsDisclaimer: '广告不是基于工作区标识或聊天历史记录的目标。{0}。',
  adsDisclaimerLearnMoreLink: '了解更多',
  actionBarNewlineTooltip: '使用 Shift+Enter 为较长的消息创建换行符',
  actionBarQuickCaptureButtonAriaLabel: 'Quick capture',
  notiChatEnd: '聊天主题已结束。',
  notiRestartChat: '在 {0} 小时内开始新主题',
  notificationAttemptingToReconnect: '正在尝试重新连接...',
  notificationProcessing: '正在尝试连接，请稍候',
  notificationLostConnection: '很抱歉，你的连接似乎已断开。',
  notificationLostConnectionCta: '是否要尝试重新连接？',
  sydneySapphireConsentDenyText: '拒绝',
  typingIndicatorStopStreamingAriaLabel: '停止流式传输',
  configurePanelFileUploadButton: 'File Upload',
  configurePanelNamePlaceHolder: 'Give your Copilot GPT a name',
  configurePanelDescriptionPlaceHolder: 'Briefly describe what this Copilot GPT does',
  configurePanelInstructionsPlaceHolder: 'Instruct your Copilot GPT how to behave. What rules should it follow? What purpose does it serve? Does it respond with a certain style?',
  configurePanelName: 'Name',
  configurePanelNameAriaLabel: 'Set a name for your Copilot GPT',
  configurePanelDescription: 'Description',
  configurePanelDescriptionAriaLabel: 'Set a description for your Copilot GPT',
  configurePanelInstructions: 'Instructions',
  configurePanelInstructionsAriaLabel: 'Set instructions for your Copilot GPT',
  configurePanelCapabilities: 'Capabilities',
  configurePanelWebSearch: 'Web browsing',
  configurePanelIsWebSearchEnabledAriaLabel: 'enable or disable the web search capability',
  configurePanelImageGenerator: 'DALL-E image generation',
  configurePanelIsImageGeneratorEnableAriaLabel: 'enable or disable the image generator capability',
  configurePanelCodeInterpreter: 'Code interpreter',
  configurePanelIsCodeInterpreterEnableAriaLabel: 'enable or disable the code interpreter capability',
  configurePanelKnowledge: 'Knowledge',
  configurePanelSaveButton: 'Save Changes',
  configurePanelSaveSuccess: 'Save Succeeded',
  configurePanelSaveFailure: 'Save Failed',
  configurePanelSaveFailureNameEmpty: 'Save Failed: Copilot GPT name is required',
  configurePanelAffirmationTips: 'By hitting \u0022Publish\u0022, I affirm that I have all rights, permissions, and authorizations required to create this Copilot GPT and that this Copilot GPT, Copilot GPT instructions, and any accompanying files comply with the Microsoft Copilot Code of Conduct and Terms and will not infringe or encourage the infringement of any third-party rights (including copyright, trademark, or publicity rights).',
  configurePanelUploadTips: 'By uploading the files, I certify that I have the right to create the Copilot GPT that doesn\u0027t infringe any third party intellectual property rights',
  gptCreatorDeleteConfirm: 'Delete',
  gptCreatorDeleteQuestion: 'Are you sure you want to delete?',
  gptCreatorDeleting: 'Deletion in progress. Please wait...',
  gptCreatorDeleteFailed: 'Failed to delete. Please try again',
  gptCreatorDeleteSucceeded: 'Deletion successful',
  gptCreatorDeleteCanceled: 'Deletion canceled',
  gptCreatorDeleteCancel: 'Cancel',
  gptCreatorLoadEditedGptFailure: 'Load Copilot GPT failed',
  gptCreatorPrivacyTermsStatement: 'Hi there! Here, you can create Copilot GPTs via chat. Simply dictate, ask questions, and correct me if I get anything wrong. By continuing your interaction with me, you are accepting the {0} and confirm you have reviewed the {1}. ',
  gptCreatorTipsTitle: 'Tips for creating a quality Copilot GPT:',
  gptCreatorTipsEnd: 'Let\u0027s start creating!',
  gptCreatorTip1: 'Try a short and catchy name that describes it\u0027s function.',
  gptCreatorTip2: 'Use clear and unambiguous language. Avoid niche acronyms, technical jargon, or overly complex vocabulary.',
  gptCreatorTip3: 'Make the prompt specific and actionable, so the Copilot GPT knows exactly what you want it to do. You can provide examples, context, or constraints to guide.',
  gptCreatorTip4: 'Use questions or statements that relevant to the user and the task at hand. You can also use keywords or phrases that the Copilot GPT is likely to recognize and associate with the desired response.',
  gptCreatorTip5: 'Make sure you have the necessary rights to any content, uploads, or instructions and used to create your Copilot GPT.',
  gptCreatorHeader: 'Copilot GPT Settings',
  gptCreatorConfigurePanel: 'Configure',
  gptCreatorCreatePanel: 'Create',
  gptCreatorPublishButton: 'Publish',
  gptCreatorCopyButtonLabel: 'Copy',
  gptCreatorPublishDropdownTitle: 'Save and publish to',
  gptCreatorConfirm: 'Confirm',
  gptCreatorPublishTypeOnlyMe: 'Only me',
  gptCreatorPublishTypeWithLink: 'Everyone with a link',
  gptCreatorPublished: 'Published!',
  gptCreatorOnlyVisitToMe: 'Only visible to me',
  gptCreatorViewGpt: 'View Copilot GPT',
  gptCreatorSeeAll: 'See all Copilot GPTs',
  gptCreatorDialogTitle: 'All Copilot GPTs',
  gptCreatorListTitle: 'My Copilot GPTs',
  gptCreatorAddGptName: 'Create a new Copilot GPT',
  gptCreatorAddGptDescription: 'Use the configure or create tool to create a custom Copilot GPT that you can keep private or share',
  gptCreatorDescriptionTitle: 'Description',
  gptCreatorPreviewButton: 'Preview Copilot GPT',
  gptCreatorDeleteButtonText: 'Delete',
  gptCreatorEditButtonText: 'Edit',
  gptCreatorChatButtonText: 'Get started',
  gptCreatorPreviewText: 'Select a Copilot GPT to preview here',
  sydneyWindowsCopilotUseTerms: '使用条款',
  sydneyCarouselCollapse: '折叠',
  sydneyCarouselTitle: '最近的聊天主题',
  messageActionsCopy: '复制',
  messageActionsCopying: '正在复制',
  messageActionsCopied: '已复制',
  messageActionsCopyError: '错误',
  messageActionsReport: '报告',
  messageActionsEditResponse: '编辑',
  tooltipPositive: '点赞',
  tooltipNegative: '不喜欢',
  tooltipShare: '共享',
  tooltipMore: '更多',
  tooltipSendToPhone: '在手机上继续',
  codeDisclaimer: 'AI 生成的代码。仔细查看和使用。 {0}.',
  codeDisclaimerLinkLabel: '有关常见问题解答的详细信息',
  exportTitle: '导出',
  exportTextTitle: '文本',
  exportPdfTitle: 'PDF',
  exportWordTitle: 'Word',
  exportWordOnlineTitle: 'Word',
  exportExcelTitle: '下载为工作簿(.xlsx)',
  exportExcelOnlineTitle: '在 Excel 中编辑',
  exportTableTitle: '表格',
  exportToastViewButtonLabel: '查看',
  exportSuccessToastTitle: '已导出文件。某些格式和图像可能无法导出。',
  exportErrorToastTitle: '导出失败',
  exportLoadingToastTitle: '正在导出...',
  exportedFileUserTitle: '用户',
  exportedFileBotTitle: '必应',
  exportedFileSourceTitle: '源',
  mobileUpsellMessage1: '扫描此 QR 码以在移动必应应用上继续此对话',
  mobileUpsellTitle1: '在手机上继续',
  visualSearchMobileUpsellLabel: '在手机上使用必应应用',
  mobileUpsellTitle2: '使用必应应用拍摄照片',
  mobileUpsellMessage2: '扫描 QR 码以在移动设备上使用必应应用拍摄此照片',
  actionBarAutoSuggestTab: 'Tab',
  actionBarAutoSuggestTap: '点击',
  actionBarKeyboardHint: '输入',
  feedbackShareAnswer: '查看此必应答案',
  feedbackShareGenerated: '查看我使用必应生成的内容',
  feedbackShowTonesButtonAriaLabel: '显示所有音调',
  feedbackHideTonesButtonAriaLabel: '隐藏所有色调',
  feedbackHidePreciseToneButtonAriaLabel: '隐藏精确',
  feedbackShareErrorToast: '共享失败。',
  serpfeedback: '反馈',
  shareConversation: '共享整个对话',
  speechAuthenticationError: '身份验证失败。请稍后重试。',
  speechNoPermissionErrorWinCopilot: '\u003cb\u003e 麦克风访问 \u003c/b\u003e\u003cbr\u003e 要使 Windows 中的 Copilot 在 Windows 中使用您的麦克风，请确保在“Windows 设置”中启用\u003cb\u003e“允许桌面应用访问麦克风”\u003c/b\u003e。 ',
  speechOnlineNotification: '语音输入由 Microsoft 联机服务处理，不会进行收集或存储。',
  speechUnknownError: '出错了。',
  refresh: '刷新',
  feedbackShareContent: '下面是我使用新的必应（全球首个 AI支持的应答引擎）生成的答案。单击可查看完整答案，然后请你也来试一试。',
  fileUploadDragAndDropLabel: '在此处删除图像或文件',
  fileUploadUnsupportedFileMessage: '此文件类型不受支持。选择文本文件，然后重试。',
  fileUploadMaxSizeLimitErrorMessage: '文件大小已超限。只能上传高达 500KB 的文件。',
  fileUploadFileNameLengthErrorMessage: 'File name length is too long.',
  fileUploadMaxSizeLimitLongContextErrorMessage: '文件大小已超限。只能上传大小不超过 10MB 的文件。',
  fileUploadMaxSizeLongContextErrorMessage: '文件大小已超限。只能上传大小不超过 {0}MB 的文件。',
  fileUploadTextFileUploadErrorMessage: '无法上传文件。',
  fileUploadWebPageInfoUploadErrorMessage: '无法从网页中提取内容。',
  fileUploadFlyoutInputboxAriaLabel: '粘贴网页 URL',
  fileUploadFlyoutTitle: '添加文本文件',
  fileUploadFlyoutUploadButtonLabel: '从此设备上传',
  fileUploadGenericErrorMessage: '无法上传该文件。请重试',
  fileUploadWebUrlLimitErrorMessage: 'Only one web url upload is allowed',
  fileUploadFileLimitErrorMessage: 'Maximum file upload limit exceeded',
  fileUploadSameFileNameErrorMessage: 'File upload with same name is not allowed',
  preview: '预览',
  toneSelectorDescription: '选择对话样式',
  toneSelectorMoreCreative: '更\\r\\n有创造力',
  toneSelectorMoreBalanced: '更\\r\\n平衡',
  toneSelectorMorePrecise: '更\\r\\n精确',
  toneSelectorFaster: '更快',
  toneSelectorWithGPT4: '使用 GPT-4',
  notificationClientIdChangedInNotebook: '你的笔记本已过期。',
  notificationClientIdChangedInNotebookCta: '开始新主题',
  notificationMaxTurnsPerDay: '很抱歉，你已达到可在 24 小时内发送到必应的邮件限制。请稍后回来查看!',
  notificationMaxTurnsPerConversation: '很抱歉，此对话已达到其限制。使用“扫除”按钮清除此内容并进行更多聊天。',
  notificationMaxTurnsPerConversationInNotebook: '很抱歉，我想我们需要继续操作!使用左侧的“新主题”按钮清除内容并重新开始。',
  notificationMaxTurnsForMuidUsers: '你已达到今天的对话限制。',
  notificationMaxTurnsForInPrivateUsers: '你已达到 inPrivate 模式的会话限制。打开非 inPrivate 窗口以继续聊天',
  notificationUnauthorizedMuidUsersCta: '登录以继续你的聊天。',
  muidUserHeaderText: '',
  muidUsersTermsCond1: '通过单击“开始使用”，并继续与必应交互，即表示你接受',
  muidUsersTermsCond1Inline: '通过继续与必应交互，你将接受 ',
  muidUsersTermsCond2: '并确认你已查看',
  muidUsersPrivacyStatement: '隐私声明',
  muidUsersTermsOfUse: '使用条款',
  muidUserGetStartedText: '开始使用',
  muidUserContinueText: '继续',
  welcomeMobSugg1: '必应如何使用 AI?',
  welcomeMobSugg2: '必应还可以做什么？',
  welcomeMobSugg3: '科技领域的最新消息是什么？',
  of: '共',
  notificationResetConversation: '很抱歉，似乎出现错误。',
  notificationResetConversationCta: '让我们重新开始吧。',
  toneSelectorCreativeTooltip: '清除对话并开始原创和富有想象力的聊天',
  toneSelectorBalancedTooltip: '清除对话并开始一个信息丰富且友好的聊天',
  toneSelectorPreciseTooltip: '清除对话并开始简洁直截了当的聊天',
  toneSelectorSuppressedTooltip: '暂时不可用。请稍后再试!',
  notificationDisengaged: '也许该换个新话题了。',
  notificationForbidden: '很抱歉，你似乎不再有权访问此功能。请几天后再次查看。',
  notificationTooManyRequests: '很抱歉，现在需求量非常大。请稍后重试。',
  notificationUnauthorized: '很抱歉，你似乎已注销。',
  notificationUnauthorizedCta: '请重新登录。',
  notificationUnauthorizedMissingDOB: '可能需要确认你的出生日期才能继续聊天。',
  notificationUnauthorizedMissingDOBCta: '在此处更新你的帐户。',
  notificationUnauthorizedChildUser: '很抱歉，必应聊天不适用于此帐户。',
  notificationUnauthorizedChildUserCta: '在 bing.com 上浏览 Web!',
  notificationMessageError: '上一条消息似乎已中断。',
  notificationMessageErrorInNotebook: '你上次的提示似乎已中断。',
  notificationSharedTip: '此对话\u003cstrong\u003e“{0}”\u003c/strong\u003e已于 {1} 与你共享',
  notificationNetworkOffline: '抱歉，你尚未连接。请检查你的网络连接并重试。',
  notificationAutoRefreshConversation: '出错了。正在解决，请稍候。',
  notificationAutoResendOnConnectionError: '你的连接暂时丢失。正在重新连接，请稍候。',
  notificationAutoRecoverOnMessageError: '很抱歉，你最后一封邮件似乎已中断。正在解决，请稍候。',
  notificationAutoRecoverOnMessageErrorInNotebook: '很抱歉，你最后一封邮件似乎已中断。正在解决，请稍候。',
  notificationContinueRecovering: '我仍在解决问题，请稍候。',
  signInCta: '登录 ',
  signInDescription: ' 以提出更多问题并进行更长的对话',
  signInDescriptionInPrivate: '打开非 inPrivate 窗口，以便进行更长的对话或提出更多问题',
  copyCodeButtonTooltip: '复制',
  autosaveConsentTitle: '启用自动保存以重新访问聊天',
  autosaveConsentBody: '你的聊天当前未自动保存。若要跨设备访问以前的对话，请使用自动保存。',
  autosaveConsentNote: '请注意，此设置将清除当前对话。',
  autosaveConsentAccept: '启用自动保存',
  autosaveConsentDeny: '否',
  autosaveOffBanner: '自动保存当前已关闭',
  personalConsentTitle: '启用个性化以获得更好的答案',
  personalConsentBody: '允许必应使用最近必应聊天对话中的见解来提供个性化的响应。',
  personalConsentAccept: '打开',
  personalConsentDeny: '否',
  personalOffBanner: '个性化当前处于关闭状态',
  personalOnBanner: '个性化当前处于启用状态',
  personalOnUndoBanner: '个性化设置已打开',
  personalOffUndoBanner: '个性化设置已关闭',
  personalConsentUndo: '撤消',
  personalConsentTurnOff: '禁用',
  threadsSharedOnDate: '于 {0} 共享',
  threadsMore: '更多',
  threadsExportPanelTitle: '选择格式',
  threadsExportPanelAriaLabel: '选择',
  threadsAADMSARedirectConfirm: '切换用户配置',
  threadsAADMSARedirectDescription: '正在使用 Microsoft 帐户保存你的对话历史记录。下次使用个人帐户登录时，它将在此处显示。',
  privateThreadConvDefaultTitle: '未保存的对话',
  threadsCancel: '取消',
  threadsChatHistory: '聊天记录',
  threadsConfirm: '确认',
  threadsDaysAgo: '{0} 天前',
  threadsDefaultChatName: '无标题的聊天',
  threadsDelete: '删除',
  threadsDescription: 'AI 支持的助手必应现可自动保存聊天。你可以从任何设备、桌面或移动设备访问聊天，无缝地继续。',
  threadsDescriptionNote: '请注意，除非专门保存，否则所有聊天将在 90 天内自动删除。',
  threadsEdit: '重命名',
  threadsLoad: '加载聊天',
  threadsMinimizeRecent: '最小化最近的聊天',
  threadsMinimizeSaved: '最小化保存的聊天',
  threadsPreview: '预览',
  threadsPreviewText: '跳回最近聊天',
  threadsRecentTitle: '最近的活动',
  threadsRecentTitleShort: '最近使用',
  threadsSavedTitle: '已保存',
  threadsSeeAllRecent: '查看所有最近的聊天',
  threadsSeeAllSaved: '查看所有保存的聊天',
  threadsTitle: '聊天',
  threadsTitleForFlux: '菜单',
  threadsYesterday: '昨天',
  threads2TLastAccessed: '上次应答时间',
  threads2TInfoChanged: '此信息可能已更改，因为',
  threads2TArchivedText: '屏幕截图',
  threads2TReloadDescription: '单击“重新加载”以显示来自 Web 的最新信息',
  threads2TFailedSearch: '请参阅最新 Bing.com',
  threads2TReload: '搜索 Bing.com',
  injectedActionCardTitle: '就此页面进行聊天?',
  injectedActionCardConfirm: '发送',
  injectedActionCardDeny: '忽略',
  webPageContextPrefix: '已访问网站',
  useGPT4SwitchLabel: '使用 GPT-4',
  switchGPT4Label: 'GPT-4',
  switchGPT4TurboLabel: 'GPT-4 Turbo',
  zeroInputSuggestionFallback1: '哪款咖啡研磨机评价最好？',
  zeroInputSuggestionFallback2: '对于一个预算有限的六口之家来说，会首选哪三款车型？',
  zeroInputSuggestionFallback3: '写一个我的同事会觉得有趣的笑话',
  zeroInputSuggestionFallback4: '下一流行趋势是什么？我应该在哪里购物可以找到它？',
  zeroInputSuggestionFallback5: '撰写关于鱼和青蛙寻找爱的原创寓言故事',
  zeroInputSuggestionFallback6: '创建一个表，帮助我计划接下来两周的就餐',
  zeroInputSuggestionFallback7: '为具有讽刺风格的新社交媒体平台创建一个口号',
  zeroInputSuggestionCategory1: '商店',
  zeroInputSuggestionCategory2: '比较',
  zeroInputSuggestionCategory3: '大笑',
  zeroInputSuggestionCategory4: '聊天',
  zeroInputSuggestionCategory5: '写入',
  zeroInputSuggestionCategory6: '组织',
  zeroInputSuggestionCategory7: '创建',
  zeroInputDescription: '必应是 AI 支持的网上助手',
  discoverMessageItemTitle: '📝 一起重写文本',
  discoverMessageItemContent: '尝试从页面中选择文本以查看我们可以一起执行的操作',
  pluginTitle: '插件',
  bookNowWithOpenTable: '立即使用 OpenTable 预订',
  scrollLeft: '向左滚动',
  scrollRight: '向右滚动',
  responses: '回复',
  personalizationConsentTitleText: '已为你设置个性化对话',
  personalizationConsentTitleTextEu: '已为你设置个性化对话',
  personalizationConsentContentText1: '必应使用聊天历史记录中的 Insights 使对话成为独一无二的对话。',
  personalizationConsentContentText1Eu: '共享聊天历史记录时，必应会根据你和你的兴趣定制回复。',
  personalizationConsentContentText2: '。',
  personalizationConsentLearnMoreText: '在我们的常见问题解答中了解详细信息',
  personalizationConsentLearnMoreTextEu: '了解有关个性化的详细信息',
  personalizationConsentContentSettingsText: '随时在“必应设置”中关闭个性化设置。',
  personalizationConsentStatusPositiveText: '已启用个性化。',
  personalizationConsentStatusNegativeText: '未启用个性化。',
  personalizationConsentSettingsText1: '若要修改，请访问',
  personalizationConsentSettingsLinkText: '必应聊天设置',
  personalizationConsentSettingsText2: '页面',
  personalizationConsentTurnOnText: '打开',
  personalizationConsentTurnOffText: '不打开',
  pluginEnabledPlugin: '已启用',
  pluginEnabledNumber: '{0} / {1}',
  pluginStartNewTopic: '开始新主题',
  pluginToChangePlugin: '更改插件',
  pluginNotificationMaxExceeded: '已启用的最大插件数',
  pluginNotificationMaxExceededV2: '已启用最大数量的插件。',
  pluginNotificationExclusive: '{0} 与 {1} 太相似。请选择一个',
  pluginNotificationExclusiveV2: '{0} 和 {1} 可以起到类似的作用。请选择一个。',
  pluginTerms: '使用条款',
  pluginPrivacy: '隐私策略',
  pluginPanelFreTitle: '插件现在可用',
  pluginPanelFreTextLabel: '新建:',
  pluginPanelFreText: '打开插件，帮助你从喜欢的品牌中查找餐厅预订、航班等。',
  pluginPanelFreDismiss: '忽略',
  pluginPanelAlertTitle: '插件在“平衡”模式下不可用',
  pluginPanelAlertCta: '重置对话 ',
  pluginPanelAlertSubtitle: '并使用“更多创意”或“更精确”对话样式，然后重试。',
  pluginLimitationDataShared: '将与你选择的插件共享数据。',
  pluginLimitationTitle: '将插件与必应 AI 配合使用',
  pluginLimitationMax: '最多为任意一个对话线程选择 3 个插件。',
  pluginLimitationMaxV2: '为对话最多选择 {0} 个插件。',
  pluginLimitationLock: '在选择“新建主题”进行更改之前，插件会锁定到对话中。',
  pluginLimitationLockV2: '若要在开始对话后更改插件，请选择 {0}。',
  pluginPanelNolimit: '禁用 {0} 不会影响插件限制',
  pluginRevocationReason: '由于违反 Microsoft 策略，此插件被暂时禁用',
  activatetoUsePlugins: '激活 {0} 以使用插件',
  threadsToggleExpansion: '切换扩展',
  threadsEnabledPlugins: '已启用插件:',
  bingSearchDisabled: '搜索**已禁用**。',
  bingSearchDisabledforMessage: '搜索已禁用',
  activateSearch: '启动新主题并激活搜索',
  visualSearchFlyoutTitle: '添加图像',
  visualSearchGenericErrorMessage: '无法上传该文件。请重试。',
  visualSearchUnsupportedFileMessage: '不支持此文件类型。选择图像文件，然后重试。',
  visualSearchInvalidUrlMessage: '抱歉 - 你提供的 URL 似乎无效。请重试',
  visualSearchFlyoutInputboxAriaLabel: '粘贴图像或链接',
  visualSearchFlyoutTakePhotoButtonLabel: '拍照',
  visualSearchDragAndDropLabel: '将图片拖至此处',
  visualSearchFlyoutUploadButtonLabel: '从此设备上传',
  raiDisclaimerLabel: 'AI 生成的内容可能不正确',
  slimHeaderTitle: '查看 AI 支持的新必应的解答',
  starterPageTitle: '必应是 AI 支持的网上助手',
  starterDescription: '用你自己的语言与必应聊天。如果感到卡住，请选择以下开场白之一，以观察必应是如何运作的：',
  starterSubtitle1: '进行对话',
  starterSubtitle2: '释放你的创造力',
  starterSubtitle3: '更智能地搜索',
  starterContent1: '像日常聊天一样使用自然语句并询问后续内容时，必应效果最佳',
  starterContent2: '无论是用图像还是文字，必应可以通过让你的愿景变为现实来激发你的创造力',
  starterContent3: '与必应聊天是一种新搜索方式。让必应汇总 Web 内容并提供答案',
  starterChatQuery1: '你认为其他行星上有生命吗？地球的独特之处是什么？',
  starterChatQuery2: '如果我睡眠遇到问题，但只在夏天发生，是怎么回事？',
  starterChatQuery3: '我想开辟一个花园，但我对此一无所知。第一步需要做什么？',
  starterChatQuery4: '你认为鳄鱼或灰熊会在搏斗中获胜吗？',
  starterChatQuery5: '我最近读了很多非虚构类书籍。你能帮我找到我喜欢的主题的虚构类版本吗？',
  starterChatQuery6: '让我们进行一次对话，其中你说的所有内容都是用表情符号编写的。',
  starterChatQuery7: '我一直在考虑搬到一个新的地方。你认为我应该去哪儿？',
  starterChatQuery8: '我曾经写过日记，但最近经常偷懒。我如何才能保持习惯？',
  starterChatQuery9: '你是否会像人类一样做梦？你会梦到什么？',
  starterChatQuery10: '是否可能同时发生地震、海啸和火山喷发？',
  starterCreateQuery1: '我有一只黑毛的小狗，除了肚子上的毛是白色的。请将它画成卡通形象。',
  starterCreateQuery2: '为我的 3 岁的侄女写一个睡前故事。她喜欢马和魔法，而且我认为这个故事应该押韵”',
  starterCreateQuery3: '用一位高傲自大的教授的语气撰写一篇短文，来证明月亮比太阳更好',
  starterCreateQuery4: '用印象派风格画一只在冰山上晒太阳的北极熊。它还应该在喝柠檬水',
  starterCreateQuery5: '让我们来创造一种颜色，并撰写一个社交媒体帖子向全世界介绍它',
  starterCreateQuery6: '作为由 Christian Bale 扮演的蝙蝠侠，请告诉我如何骑着摩托车应对交通',
  starterCreateQuery7: '用一位在家酿酒并引发小型爆炸的爸爸的语气，为一个新的啤酒品牌制作销售宣传',
  starterCreateQuery8: '为一家咖啡馆设计一副海报，其中包含日落并充分利用空间',
  starterCreateQuery9: '画一只身为湖上趸船船长的长颈鹿',
  starterCreateQuery10: '为一篇有关女权主义文学历史的论文撰写简介段落，并为我提供五个写作提示以继续',
  starterCompareQuery1: '为我找一份提拉米苏的菜谱，为我制作一个购物清单，然后进行排列，以便我可以在商店中快速找到配料',
  starterCompareQuery2: '为我提供的今天的本地新闻汇报，不包括体育内容”',
  starterCompareQuery3: '用五个要点总结最新的 AI 研究，并得出接下来的发展趋势的结论',
  starterCompareQuery4: '创建一个表格，用来按品牌、价格、安全功能和可能的附加设备比较最佳电动车',
  starterCompareQuery5: '这附近有儿童游乐场的最近的公园在哪里？',
  starterCompareQuery6: '为我晚上要做的意大利菜提供三种葡萄酒建议。这道菜以西红柿为主料，并且有点辣。',
  starterCompareQuery7: '为我提供 UN 的最新焦点的概要',
  starterCompareQuery8: '创建一个表格，用来比较出人意料的普利策奖获得者及其原因',
  starterCompareQuery9: '用孩子能够理解的方式介绍 Internet 的运作原理',
  starterCompareQuery10: '将“诗歌简介”这首诗翻译为法语，并用英语简要解释任何损失的含义',
  notificationMaxTurnsAndOpenEdge: '你已达到对话限制。若要继续聊天，',
  notificationMaxTurnsAndOpenEdgeCta: '在 Microsoft Edge 中打开',
  actionBarPromptGuideToolTip: '提示指南',
  actionBarAttachButtonToolTip: '附加',
  promptLibraryButtonLabel: '查看提示',
  actionBarLongPlaceholder: '询问我任何内容或键入/添加人员、文件等',
  actionBarNotebookPlaceholder: '你有什么想法?编写与 AI 协作的详细提示。使用 Shift+Enter 提交邮件。',
  thirdPartyBingChatAttribution: '由 AI 支持的必应提供的结果',
  thirdPartyRAIDisclaimer: '可能会出现意外和错误',
  thirdPartyPrivacyHyperlink: '隐私',
  thirdPartyTermsHyperlink: '条款',
  usePreciseLocation: '更新地点',
  basedOnLocation: '基于: {0}、{1}',
  basedOnYourLocation: '基于你的位置',
  locationFetchErrorMessage: '权限被拒',
  locationLearnMore: '(了解详细信息)',
  deleteAllAria: '删除全部聊天历史记录',
  deleteAll: '删除全部聊天历史记录',
  deleteAllMobile: '全部删除',
  moreActions: '更多操作',
  newTopic: '新主题',
  chatHistory: '聊天记录',
  messageLearnMoreV2: '了解详细信息',
  sunoPolicyText: '你的歌曲请求，包括其中的任何个人数据，将与 Suno 共享。使用流派和风格来描述你的请求，而不是使用特定艺术家姓名。每天最多可创建 5 首歌曲。',
  customGptWelcomeTilesQuestionDescription: 'What type of queestions can I ask?',
  customGptWelcomeTilesListDescription: 'Tell me 5 things about you',
  customGptWelcomeTilesSummarizeDescription: 'Give me a pitch about what kind of GPT you are'
};
function parseQueryParamsFromQuery (n, t) {
  var u, f, e, o;
  t === void 0 && (t = !0);
  var r = [],
    s = n && n.length > 0 ? n.split('&') : [],
    h = s.length,
    i = null;
  for (u = 0; u < h; u++)
    (f = s[u]), (e = f.indexOf('=')), e > 0 && ((i = f.substr(0, e)), i.charAt(0) == '?' && (i = i.substr(1)), i && ((i = i.toLowerCase()), (r[i] = f.substr(e + 1))));
  return t && ((o = r.first), (r.first = null == o || o == '0' ? 1 : parseInt(o))), r;
}
function parseQueryParams () {
  var n = '';
  return (
    (n = typeof Bing != 'undefined' && Bing.Url && Bing.Location ? Bing.Url.getQueryString(Bing.Location.get()) : _w.location.search.substring(1)), parseQueryParamsFromQuery(n)
  );
}
function convertQueryParamsToUrlStr (n, t) {
  t === void 0 && (t = null);
  var i = t ? t : _w.location.pathname.replace(/^\/+/, '/');
  return i + '?' + queryParamsToString(n);
}
function queryParamsToString (n) {
  for (var e, o, r, u, s, f, t = [], i = 1; i < arguments.length; i++) t[i - 1] = arguments[i];
  if (((e = []), (u = t.length), u == 0)) for (s in n) n.hasOwnProperty(s) && (t.push(s), u++);
  for (f = 0; f < u; f++) (o = t[f]), (r = n[o]), (r || r === 0) && e.push(o + '=' + r);
  return e.join('&');
}
function getCurrentQuery () {
  if (!currentQuery) {
    var n = parseQueryParams();
    currentQuery = n.q;
  }
  return currentQuery;
}
function extractDomainFromUrl (n, t, i) {
  var r, u, f, e;
  return typeof n != 'string'
    ? null
    : ((r = n),
      (u = r.indexOf('://')),
      u >= 0 && !t && ((r = r.substr(u + 3)), (u = -1)),
      (u = u >= 0 ? u + 3 : 0),
      (f = r.indexOf(':', u)),
      f >= 0 && (r = r.substr(0, f)),
      (f = r.indexOf('/', u)),
      f >= 0 && (r = r.substr(0, f)),
      (e = i ? r.indexOf('www.') : -1),
      e >= 0 && (r = r.substr(u + 4)),
      r);
}
function addCommonPersistedParams (n) {
  var i = parseQueryParams(),
    t = queryParamsToString(
      i,
      'atlahostname',
      'cdghostname',
      'thhostname',
      'testhooks',
      'adlt',
      'akamaithumb',
      'safesearch',
      'perf',
      'mockimages',
      'mobile',
      'anid',
      'isuserauth',
      'uncrunched',
      'clientid',
      'currentdate',
      'iss'
    ),
    r = n.indexOf('?') === -1 ? '?' : '&';
  return (t = t.length > 0 ? r + t : ''), n + t;
}
var currentQuery = null;
var fab_config = {
  fabStyle: 1,
  fabSbAction: 'FocusSearchBox',
  fabSbActionHover: 'None',
  fabSbActionData: 'None',
  fabTooltip: '',
  micFabAlwaysVisible: false,
  fabClickNoAS: false,
  FabAddSuggestions: false,
  DisableAlsoTryWhenHasPoleRS: false,
};
sj_be(
  _w,
  'click',
  function () {
    _G.UIWP = true;
  },
  1
);

// 设置未登录用户的 codexMUIDUser 为 true
const User_UCookieValue = CookieGet('_U')
if (User_UCookieValue == null || User_UCookieValue == undefined || User_UCookieValue == '') {
  _w['_sydConvConfig']['codexMUIDUser'] = true
}

const customChatNum = UserStoreGet('customChatNum')
if (customChatNum != 0) {
  if (User_UCookieValue == null || User_UCookieValue == undefined || User_UCookieValue == '') {
    _w['_sydConvConfig']['maxTurnsPerConversationMuidUser'] = customChatNum
  } else {
    _w['_sydConvConfig']['maxTurnsPerConversation'] = customChatNum
  }
}


if (UserStoreGet('enterpriseEnable')) {
  _w['_sydConvConfig']['disableWelcomeScreen'] = false
  _w['_sydConvConfig']['enableWelcomeScreenV2'] = false
  _w['_sydConvConfig']['enableTelemetryPrivacy'] = true
  _w['_sydConvConfig']['isMSAAuthenticated'] = false
  _w['_sydConvConfig']['isAccountLinkedWithActiveAAD'] = true
  _w['_sydConvConfig']['extraBceOptions'] = 'bcechat'
  _w['_sydConvConfig']['isBingChatForEnterprise'] = true
  _w['_sydConvConfig']['enableMessagePrivacy'] = true
  _w['_sydConvConfig']['PLoadIID'] = 'SERP.5833'
  _w['_sydConvTranslation']['warmWelcomeTitle'] = 'Bing Chat Enterprise'
  _w['_sydConvTranslation']['welcomeSubtitleText'] = '由 AI 支持的适用于 Web 的 Copilot'
  _w['_sydConvTranslation']['inputRaiLabel'] = '你的个人和公司数据在此聊天中受到保护'
}